import { homedir } from "node:os";
import { join } from "node:path";
import type { PipelineConfig } from "../config";

export const GENERATED_MARKER = "<!-- Generated by @oisincoveney/pipeline. -->";
export const GENERATED_TS_MARKER = "// Generated by @oisincoveney/pipeline.";
export const GENERATED_YAML_MARKER = "# Generated by @oisincoveney/pipeline.";
export const OWNER_MARKER_PREFIX = "<!-- @oisincoveney/pipeline:";
export const OWNER_TS_MARKER_PREFIX = "// @oisincoveney/pipeline:";
export const OWNER_YAML_MARKER_PREFIX = "# @oisincoveney/pipeline:";
export const AGENTS_MD_START = "<!-- @oisincoveney/pipeline:agents:start -->";
export const AGENTS_MD_END = "<!-- @oisincoveney/pipeline:agents:end -->";
export const SINGLE_OPENCODE_PLUGIN_ARRAY_RE =
  /\n {2}"plugin": \[\n {4}("[^"]+")\n {2}\]/;
export const OPENCODE_PROJECT_CONFIG_PATH = ".opencode/opencode.json";
export const CLAUDE_PROJECT_CONFIG_PATH = ".claude/settings.json";
const OPENCODE_COMMAND_PREFIX = "moka-";
export const ENTRYPOINT_PATH_PATTERNS: Record<ActiveCommandHost, RegExp[]> = {
  opencode: [/^\.opencode\/commands\/(?:moka-)?([^/]+)\.md$/],
  "claude-code": [/^\.claude\/commands\/(?:moka-)?([^/]+)\.md$/],
};
export const COMMAND_HOSTS = ["opencode", "claude-code"] as const;

export type ActiveCommandHost = (typeof COMMAND_HOSTS)[number];
export type CommandHostSelection = ActiveCommandHost | "all";
/**
 * Where generated harness resources are written.
 * - "global" (default): the per-machine host config dirs (~/.claude,
 *   ~/.config/opencode, ~/.codex). One harness shared by every repo on the
 *   machine/container.
 * - "project": repo-local .claude/.opencode/.codex dirs (opt-in).
 */
export type HarnessScope = "global" | "project";
export const DEFAULT_HARNESS_SCOPE: HarnessScope = "global";

/**
 * The per-machine host config dirs. Each honors the same env var the host tool
 * itself uses to relocate its config (so containers/CI can redirect, and so
 * does our test suite): Claude Code reads `CLAUDE_CONFIG_DIR`, Codex reads
 * `CODEX_HOME`, OpenCode reads `OPENCODE_CONFIG_DIR`/`XDG_CONFIG_HOME`.
 */
export function claudeGlobalConfigDir(): string {
  return process.env.CLAUDE_CONFIG_DIR ?? join(homedir(), ".claude");
}

export function codexGlobalConfigDir(): string {
  return process.env.CODEX_HOME ?? join(homedir(), ".codex");
}

export function opencodeGlobalConfigDir(): string {
  return (
    process.env.OPENCODE_CONFIG_DIR ??
    join(process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"), "opencode")
  );
}

function stripPrefix(value: string, prefix: string): string {
  if (value === prefix) {
    return "";
  }
  return value.startsWith(`${prefix}/`)
    ? value.slice(prefix.length + 1)
    : value;
}

/**
 * Resolve a repo-relative harness path (e.g. ".claude/agents/x.md",
 * ".opencode/opencode.json", "AGENTS.md") to its absolute on-disk target for
 * the given scope.
 *
 * - project: rooted at `cwd` (the repo) — the historical behaviour.
 * - global: rooted at the host-native per-machine config dirs. `.claude/*` →
 *   the Claude config dir, `.codex/*` → the Codex config dir, and `.opencode/*`
 *   plus bare root files (e.g. AGENTS.md, which OpenCode reads globally) → the
 *   OpenCode config dir. The global `.opencode` and `~/.config/opencode`
 *   layouts use identical subdir names, so this is a pure prefix rebase.
 */
export function resolveHarnessTarget(
  scope: HarnessScope,
  cwd: string,
  relPath: string
): string {
  if (scope === "project") {
    return join(cwd, relPath);
  }
  const normalized = relPath.replaceAll("\\", "/");
  if (normalized === ".claude" || normalized.startsWith(".claude/")) {
    return join(claudeGlobalConfigDir(), stripPrefix(normalized, ".claude"));
  }
  if (normalized === ".codex" || normalized.startsWith(".codex/")) {
    return join(codexGlobalConfigDir(), stripPrefix(normalized, ".codex"));
  }
  return join(opencodeGlobalConfigDir(), stripPrefix(normalized, ".opencode"));
}
export type InstallAction =
  | "conflict"
  | "create"
  | "delete"
  | "unchanged"
  | "update";

export interface CommandInstallPlanItem {
  action: InstallAction;
  host: ActiveCommandHost;
  invocation: string;
  path: string;
}

export interface InstallCommandsOptions {
  check?: boolean;
  cwd?: string;
  dryRun?: boolean;
  force?: boolean;
  host?: CommandHostSelection;
  scope?: HarnessScope;
}

export interface InstallCommandsResult {
  items: CommandInstallPlanItem[];
}

export interface InstallCommandsContext {
  cwd: string;
  definitions: CommandDefinition[];
  host: CommandHostSelection;
  scope: HarnessScope;
  wantedPaths: Set<string>;
}

export interface CommandDefinition {
  block?: {
    end: string;
    start: string;
  };
  content: string;
  host: ActiveCommandHost;
  invocation: string;
  path: string;
}

/**
 * Result returned by a host adapter's mergeDefinition hook.
 * ok=true carries merged content; ok=false signals an unresolvable conflict.
 */
export interface MergeDefinitionResult {
  content: string;
  ok: boolean;
}

/**
 * A HostAdapter encapsulates everything the install orchestrator needs from a
 * single command host (e.g. opencode). Adding a new host is a single-object
 * affair: implement this interface and register the adapter in install-commands.ts.
 */
export interface HostAdapter {
  /** Produce the full set of CommandDefinitions for the given config + cwd. */
  definitions(config: PipelineConfig, cwd: string): CommandDefinition[];
  /** The host identifier this adapter serves. */
  readonly host: ActiveCommandHost;
  /**
   * Optional hook: return true if the orchestrator should treat this definition
   * as always-forced (i.e. skip conflict detection even without --force).
   * Defaults to false when absent.
   */
  isAlwaysForced?(definition: CommandDefinition): boolean;
  /**
   * Optional hook invoked when the target file already exists on disk.
   * If present, the adapter may merge definition.content with existingContent
   * (e.g. preserving user-authored fields in a JSON config).
   * Return undefined to fall back to the default overwrite behaviour.
   * Return { ok: false, content: _ } to surface a conflict without writing.
   */
  mergeDefinition?(
    definition: CommandDefinition,
    existingContent: string
  ): MergeDefinitionResult | undefined;
  /**
   * Filesystem roots that may contain generated files owned by this host.
   * The orchestrator scans these roots to detect and remove obsolete files.
   */
  readonly resourceRoots: string[];
}

// ---------------------------------------------------------------------------
// Host-neutral config extraction helpers — usable by any HostAdapter
// ---------------------------------------------------------------------------

export type EntrypointEntry = [string, PipelineConfig["entrypoints"][string]];
export type ProfileEntry = [string, PipelineConfig["profiles"][string]];

export function profileEntries(config: PipelineConfig): ProfileEntry[] {
  return Object.entries(config.profiles).sort(([a], [b]) => a.localeCompare(b));
}

export function entrypointEntries(config: PipelineConfig): EntrypointEntry[] {
  const entries = Object.entries(config.entrypoints);
  return entries.length > 0
    ? entries
    : [
        [
          "execute",
          {
            description: "Run the configured pipeline workflow",
            workflow: config.default_workflow,
          },
        ],
      ];
}

export function entrypointDescription(
  id: string,
  entrypoint: PipelineConfig["entrypoints"][string]
): string {
  return entrypoint.description ?? `Run the ${id} workflow`;
}

export function instructionsPointer(
  actor: PipelineConfig["profiles"][string]
): string {
  if (actor.instructions.path) {
    return `Instructions: ${actor.instructions.path}`;
  }
  return `Instructions:\n${actor.instructions.inline ?? ""}`;
}

export function compactLines(lines: Array<string | undefined>): string[] {
  return lines.filter((line): line is string => line !== undefined);
}

export function invocationForHost(
  host: ActiveCommandHost,
  entrypointId = "execute"
): string {
  const prefix: Record<ActiveCommandHost, string> = {
    opencode: "/",
    "claude-code": "/",
  };
  return `${prefix[host]}${commandIdForHost(host, entrypointId)} <task description>`;
}

export function commandIdForHost(
  host: ActiveCommandHost,
  entrypointId: string
): string {
  if (host === "opencode" || host === "claude-code") {
    return `${OPENCODE_COMMAND_PREFIX}${entrypointId}`;
  }
  return entrypointId;
}
