export const GENERATED_MARKER = "<!-- Generated by @oisincoveney/pipeline. -->";
export const GENERATED_TS_MARKER = "// Generated by @oisincoveney/pipeline.";
export const GENERATED_YAML_MARKER = "# Generated by @oisincoveney/pipeline.";
export const OWNER_MARKER_PREFIX = "<!-- @oisincoveney/pipeline:";
export const OWNER_TS_MARKER_PREFIX = "// @oisincoveney/pipeline:";
export const OWNER_YAML_MARKER_PREFIX = "# @oisincoveney/pipeline:";
export const AGENTS_MD_START = "<!-- @oisincoveney/pipeline:agents:start -->";
export const AGENTS_MD_END = "<!-- @oisincoveney/pipeline:agents:end -->";
export const SINGLE_OPENCODE_PLUGIN_ARRAY_RE =
  /\n {2}"plugin": \[\n {4}("[^"]+")\n {2}\]/;
export const OPENCODE_PROJECT_CONFIG_PATH = ".opencode/opencode.json";
export const CLAUDE_PROJECT_CONFIG_PATH = ".claude/settings.json";
const OPENCODE_COMMAND_PREFIX = "moka-";
export const ENTRYPOINT_PATH_PATTERNS: Record<ActiveCommandHost, RegExp[]> = {
  opencode: [/^\.opencode\/commands\/(?:moka-)?([^/]+)\.md$/],
  "claude-code": [/^\.claude\/commands\/(?:moka-)?([^/]+)\.md$/],
};
export const COMMAND_HOSTS = ["opencode", "claude-code"] as const;

export type ActiveCommandHost = (typeof COMMAND_HOSTS)[number];
export type CommandHostSelection = ActiveCommandHost | "all";
export type InstallAction =
  | "conflict"
  | "create"
  | "delete"
  | "unchanged"
  | "update";

export interface CommandInstallPlanItem {
  action: InstallAction;
  host: ActiveCommandHost;
  invocation: string;
  path: string;
}

export interface InstallCommandsOptions {
  check?: boolean;
  cwd?: string;
  dryRun?: boolean;
  force?: boolean;
  host?: CommandHostSelection;
}

export interface InstallCommandsResult {
  items: CommandInstallPlanItem[];
}

export interface InstallCommandsContext {
  cwd: string;
  definitions: CommandDefinition[];
  host: CommandHostSelection;
  wantedPaths: Set<string>;
}

export interface CommandDefinition {
  block?: {
    end: string;
    start: string;
  };
  content: string;
  host: ActiveCommandHost;
  invocation: string;
  path: string;
}

export function invocationForHost(
  host: ActiveCommandHost,
  entrypointId = "execute"
): string {
  const prefix: Record<ActiveCommandHost, string> = {
    opencode: "/",
    "claude-code": "/",
  };
  return `${prefix[host]}${commandIdForHost(host, entrypointId)} <task description>`;
}

export function commandIdForHost(
  host: ActiveCommandHost,
  entrypointId: string
): string {
  if (host === "opencode" || host === "claude-code") {
    return `${OPENCODE_COMMAND_PREFIX}${entrypointId}`;
  }
  return entrypointId;
}
