import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { installCommands, parseCommandHost } from "../src/install-commands";

const COMMAND_FRONTMATTER_RE =
  /^---\n[\s\S]*?description: [\s\S]*?\n---\n<!-- Generated by @oisincoveney\/pipeline\. -->/;

const ENTRYPOINT_COMMAND_SURFACES = [
  ".opencode/commands/moka-quick.md",
  ".opencode/commands/moka-execute.md",
  ".opencode/commands/moka-inspect.md",
];

describe("installCommands", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "pipeline-commands-"));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("installs command adapters from package config without repo pipeline files", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(existsSync(join(dir, ".pipeline"))).toBe(false);
    expect(result.items.map((item) => item.path)).toContain(
      ".opencode/commands/moka-execute.md"
    );
    expect(result.items.map((item) => item.path)).toContain(
      ".opencode/commands/moka-quick.md"
    );
    expect(existsSync(join(dir, ".agents/skills/execute/SKILL.md"))).toBe(
      false
    );
    expect(existsSync(join(dir, ".opencode/commands/moka-quick.md"))).toBe(
      true
    );
    expect(existsSync(join(dir, ".opencode/commands/pipe.md"))).toBe(false);
    expect(existsSync(join(dir, ".opencode/commands/epic.md"))).toBe(false);
  });

  it("installs all generated host resources from package defaults", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(result.items.every((item) => item.action === "create")).toBe(true);
    expect(result.items.map((item) => item.path)).toEqual([
      ".opencode/commands/moka-quick.md",
      ".opencode/commands/moka-execute.md",
      ".opencode/commands/moka-inspect.md",
      ".opencode/opencode.json",
      ".opencode/agents/MoKa Orchestrator.md",
      ".opencode/agents/MoKa Acceptance Reviewer.md",
      ".opencode/agents/MoKa Code Writer.md",
      ".opencode/agents/MoKa Inspector.md",
      ".opencode/agents/MoKa Learner.md",
      ".opencode/agents/MoKa Researcher.md",
      ".opencode/agents/MoKa Schedule Planner.md",
      ".opencode/agents/MoKa Test Writer.md",
      ".opencode/agents/MoKa Thermo Nuclear Reviewer.md",
      ".opencode/agents/MoKa Verifier.md",
      ".opencode/plugins/pipeline-goal-context.ts",
      ".claude/commands/moka-quick.md",
      ".claude/commands/moka-execute.md",
      ".claude/commands/moka-inspect.md",
      ".claude/agents/moka-inspector.md",
      ".claude/settings.json",
      "AGENTS.md",
    ]);
    for (const item of result.items) {
      expect(existsSync(join(dir, item.path))).toBe(true);
    }
    expect(
      readFileSync(join(dir, ".opencode/commands/moka-execute.md"), "utf8")
    ).toMatch(COMMAND_FRONTMATTER_RE);
    const opencode = JSON.parse(
      readFileSync(join(dir, ".opencode/opencode.json"), "utf8")
    );
    expect(opencode.lsp).toBe(true);
    expect(opencode.plugin).toEqual([
      "@devtheops/opencode-plugin-otel@1.1.0",
      "@prevalentware/opencode-goal-plugin",
      "oc-codex-multi-auth@6.3.2",
    ]);
    expect(Object.keys(opencode.provider.openai.models)).toEqual([
      "gpt-5.5-none",
      "gpt-5.5-low",
      "gpt-5.5-medium",
      "gpt-5.5-high",
      "gpt-5.5-xhigh",
    ]);
    expect(
      opencode.provider.openai.models["gpt-5.5-xhigh"].options
    ).toMatchObject({
      reasoningEffort: "xhigh",
      reasoningSummary: "detailed",
      store: false,
    });
    expect(existsSync(join(dir, ".opencode/agents/MoKa Orchestrator.md"))).toBe(
      true
    );
    const inspector = readFileSync(
      join(dir, ".opencode/agents/MoKa Inspector.md"),
      "utf8"
    );
    expect(inspector).toContain("mode: all");
    expect(inspector).toContain("hidden: false");
    expect(inspector).toContain("skill:");
    expect(inspector).toContain("research: allow");
    expect(inspector).toContain("task: deny");
    expect(existsSync(join(dir, ".opencode/skills"))).toBe(false);
    const localPlugin = readFileSync(
      join(dir, ".opencode/plugins/pipeline-goal-context.ts"),
      "utf8"
    );
    expect(localPlugin).toContain("Generated by @oisincoveney/pipeline.");
    expect(localPlugin).toContain("@oisincoveney/pipeline:host=opencode");
    expect(localPlugin).toContain("PipelineGoalContext");
    expect(localPlugin).toContain("experimental.session.compacting");
    const quickCommand = readFileSync(
      join(dir, ".opencode/commands/moka-quick.md"),
      "utf8"
    );
    const executeCommand = readFileSync(
      join(dir, ".opencode/commands/moka-execute.md"),
      "utf8"
    );
    expect(quickCommand).toContain("agent: MoKa Orchestrator");
    expect(quickCommand).toContain("Configured orchestrator:");
    expect(quickCommand).toContain(
      "Generate a schedule for entrypoint `quick`"
    );
    expect(quickCommand).toContain(
      "Run `moka submit --quick <task description>`"
    );
    expect(quickCommand).toContain(
      "Configure the target in `~/.config/moka/config.yaml`"
    );
    expect(executeCommand).toContain(
      "Generate a schedule for entrypoint `execute`"
    );
    expect(executeCommand).not.toContain(
      "Run workflow `inspect` for the user task."
    );
  });

  it("makes Moka specialist agents selectable primary agents and subagents", async () => {
    await installCommands({ cwd: dir, host: "all" });

    for (const agentName of [
      "MoKa Acceptance Reviewer",
      "MoKa Code Writer",
      "MoKa Inspector",
      "MoKa Learner",
      "MoKa Researcher",
      "MoKa Schedule Planner",
      "MoKa Test Writer",
      "MoKa Thermo Nuclear Reviewer",
      "MoKa Verifier",
    ]) {
      const content = readFileSync(
        join(dir, `.opencode/agents/${agentName}.md`),
        "utf8"
      );

      expect(content).toContain("mode: all");
      expect(content).toContain("hidden: false");
    }
  });

  it("installs the pipeline gateway project config for OpenCode", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(result.items).toContainEqual(
      expect.objectContaining({
        action: "create",
        host: "opencode",
        path: ".opencode/opencode.json",
      })
    );

    const opencode = JSON.parse(
      readFileSync(join(dir, ".opencode/opencode.json"), "utf8")
    );
    expect(opencode.mcp["pipeline-gateway"]).toMatchObject({
      enabled: true,
      oauth: false,
      type: "remote",
      url: "https://pipeline-mcp.momokaya.ee/mcp/",
    });
    expect(opencode.mcp["pipeline-gateway"].headers).toEqual({
      Authorization: "{env:PIPELINE_MCP_GATEWAY_AUTHORIZATION}",
    });
  });

  it("renders scheduled entrypoints as CLI schedule generation instructions", async () => {
    await installCommands({ cwd: dir, host: "all" });

    for (const path of [
      ".opencode/commands/moka-quick.md",
      ".opencode/commands/moka-execute.md",
    ]) {
      const content = readFileSync(join(dir, path), "utf8");
      expect(content).toContain("Generate a schedule for entrypoint");
      expect(content).toContain(
        "Submit Momokaya work as Argo Workflows through `moka submit` and `moka submit --quick`"
      );
      expect(content).toContain("Use `moka submit ");
      expect(content).toContain("--kubeconfig <path>");
      expect(content).not.toContain("--local <task description>");
    }
  });

  it("generates a managed AGENTS.md block with repo-scoped pipeline memory guidance", async () => {
    await installCommands({ cwd: dir, host: "opencode" });

    const content = readFileSync(join(dir, "AGENTS.md"), "utf8");
    expect(content).toContain("<!-- @oisincoveney/pipeline:agents:start -->");
    expect(content).toContain("<!-- @oisincoveney/pipeline:agents:end -->");
    expect(content).toContain(
      "This repository uses package-owned `@oisincoveney/pipeline` config."
    );
    expect(content).toContain(
      "Use `/moka-quick`, `/moka-execute`, or `/moka-inspect`"
    );
    expect(content).toContain("Call `qdrant-find` before research");
    expect(content).toContain("Call `qdrant-store` during LEARN");
    expect(content).toContain(`collection_name: ${basename(dir)}`);
    expect(content).toContain("metadata");
    expect(content).toContain("repo");
    expect(content).toContain("phase");
    expect(content).toContain("outcome");
  });

  it("updates only the managed AGENTS.md block and preserves project-authored instructions", async () => {
    writeFileSync(
      join(dir, "AGENTS.md"),
      ["# Project rules", "", "- Keep this custom rule.", ""].join("\n")
    );

    await installCommands({ cwd: dir, host: "opencode" });
    const first = readFileSync(join(dir, "AGENTS.md"), "utf8");

    expect(first).toContain("# Project rules");
    expect(first).toContain("- Keep this custom rule.");
    expect(first).toContain("<!-- @oisincoveney/pipeline:agents:start -->");

    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "opencode",
    });
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("preserves repo-local OpenCode auth plugin and gateway config", async () => {
    mkdirSync(join(dir, ".opencode"), { recursive: true });
    const existingGateway = {
      enabled: true,
      headers: { Authorization: "{env:CUSTOM_GATEWAY_TOKEN}" },
      oauth: false,
      timeout: 30_000,
      type: "remote",
      url: "https://custom.example/mcp",
    };
    writeFileSync(
      join(dir, ".opencode/opencode.json"),
      `${JSON.stringify(
        {
          $schema: "https://opencode.ai/config.json",
          lsp: false,
          mcp: {
            "pipeline-gateway": existingGateway,
          },
          plugin: ["repo-local-auth-plugin"],
        },
        null,
        2
      )}\n`
    );

    const result = await installCommands({
      cwd: dir,
      force: true,
      host: "all",
    });

    expect(result.items).toContainEqual(
      expect.objectContaining({
        action: "update",
        host: "opencode",
        path: ".opencode/opencode.json",
      })
    );
    const opencode = JSON.parse(
      readFileSync(join(dir, ".opencode/opencode.json"), "utf8")
    );
    expect(opencode.lsp).toBe(false);
    expect(opencode.mcp["pipeline-gateway"]).toEqual(existingGateway);
    expect(opencode.plugin).toEqual([
      "repo-local-auth-plugin",
      "@devtheops/opencode-plugin-otel@1.1.0",
      "@prevalentware/opencode-goal-plugin",
      "oc-codex-multi-auth@6.3.2",
    ]);
  });

  it("is idempotent and check passes after install", async () => {
    await installCommands({ cwd: dir, host: "all" });
    writeFileSync(
      join(dir, ".opencode/commands/execute.md"),
      [
        "---",
        "description: Legacy execute command.",
        "---",
        "<!-- Generated by @oisincoveney/pipeline. -->",
        "<!-- @oisincoveney/pipeline:host=opencode -->",
        "",
      ].join("\n")
    );
    mkdirSync(join(dir, ".opencode/skills/legacy"), { recursive: true });
    writeFileSync(
      join(dir, ".opencode/skills/legacy/SKILL.md"),
      [
        "<!-- Generated by @oisincoveney/pipeline. -->",
        "<!-- @oisincoveney/pipeline:host=opencode -->",
        "",
      ].join("\n")
    );

    const second = await installCommands({ cwd: dir, host: "all" });
    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "all",
    });

    expect(second.items).toContainEqual(
      expect.objectContaining({
        action: "delete",
        path: ".opencode/commands/execute.md",
      })
    );
    expect(second.items).toContainEqual(
      expect.objectContaining({
        action: "delete",
        path: ".opencode/skills/legacy/SKILL.md",
      })
    );
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
    expect(checked.items.map((item) => item.path)).not.toContain(
      ".opencode/commands/execute.md"
    );
    expect(checked.items.map((item) => item.path)).not.toContain(
      ".opencode/skills/legacy/SKILL.md"
    );
  });

  it("preserves unowned OpenCode skill files", async () => {
    await installCommands({ cwd: dir, host: "all" });
    mkdirSync(join(dir, ".opencode/skills/execute"), { recursive: true });
    writeFileSync(
      join(dir, ".opencode/skills/execute/SKILL.md"),
      [
        "---",
        "name: execute",
        "description: Installed execute skill.",
        "---",
        "",
        "# Execute",
        "",
      ].join("\n")
    );

    const second = await installCommands({ cwd: dir, host: "all" });

    expect(second.items.map((item) => item.path)).not.toContain(
      ".opencode/skills/execute/SKILL.md"
    );
    expect(
      readFileSync(join(dir, ".opencode/skills/execute/SKILL.md"), "utf8")
    ).toContain("Installed execute skill.");
  });

  it("dry-run reports creates for entrypoint command surfaces without writing files", async () => {
    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "all",
    });

    for (const path of ENTRYPOINT_COMMAND_SURFACES) {
      expect(result.items).toContainEqual(
        expect.objectContaining({ action: "create", path })
      );
      expect(existsSync(join(dir, path))).toBe(false);
    }
    expect(existsSync(join(dir, ".pipeline"))).toBe(false);
  });

  it("check fails when commands are missing", async () => {
    await expect(
      installCommands({ check: true, cwd: dir, host: "opencode" })
    ).rejects.toThrow("not up to date");
  });

  it("dry-run reports conflicts without throwing or overwriting", async () => {
    const path = join(dir, ".opencode/commands/moka-quick.md");
    mkdirSync(join(dir, ".opencode/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "opencode",
    });

    expect(result.items[0]).toMatchObject({
      action: "conflict",
      host: "opencode",
      path: ".opencode/commands/moka-quick.md",
    });
    expect(readFileSync(path, "utf8")).toBe("manual command");
  });

  it("refuses to overwrite manually edited files unless forced", async () => {
    const path = join(dir, ".opencode/commands/moka-quick.md");
    mkdirSync(join(dir, ".opencode/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    await expect(
      installCommands({ cwd: dir, host: "opencode" })
    ).rejects.toThrow("Refusing to overwrite");

    const forced = await installCommands({
      cwd: dir,
      force: true,
      host: "opencode",
    });

    expect(forced.items[0]).toMatchObject({
      action: "update",
      host: "opencode",
      path: ".opencode/commands/moka-quick.md",
    });
    expect(readFileSync(path, "utf8")).toContain(
      "Generated by @oisincoveney/pipeline"
    );
  });

  it("validates host names through Commander parser hook", () => {
    expect(parseCommandHost("all")).toBe("all");
    expect(parseCommandHost("opencode")).toBe("opencode");
    expect(parseCommandHost("claude-code")).toBe("claude-code");
    expect(() => parseCommandHost("bad")).toThrow('Unsupported host "bad"');
  });

  it("installs Claude Code command and agent adapters", async () => {
    const result = await installCommands({ cwd: dir, host: "claude-code" });

    expect(result.items.every((item) => item.action === "create")).toBe(true);
    const paths = result.items.map((item) => item.path);
    expect(paths).toContain(".claude/commands/moka-execute.md");
    expect(paths).toContain(".claude/commands/moka-quick.md");
    expect(paths).toContain(".claude/commands/moka-inspect.md");
    expect(paths).toContain(".claude/agents/moka-inspector.md");
    expect(paths).toContain(".claude/settings.json");
    expect(existsSync(join(dir, ".claude/skills"))).toBe(false);

    const execute = readFileSync(
      join(dir, ".claude/commands/moka-execute.md"),
      "utf8"
    );
    expect(execute).toContain("allowed-tools: 'Task, Bash(opencode run *)'");
    expect(execute).toContain("argument-hint: <task description>");
    expect(execute).toContain("`execute` skill");
    expect(execute).toContain("Generate a schedule for entrypoint `execute`");

    const inspect = readFileSync(
      join(dir, ".claude/commands/moka-inspect.md"),
      "utf8"
    );
    expect(inspect).toContain("Run workflow `inspect` for the user task.");
    expect(inspect).toContain("Task subagent_type=moka-inspector");

    const agent = readFileSync(
      join(dir, ".claude/agents/moka-inspector.md"),
      "utf8"
    );
    expect(agent).toContain("name: moka-inspector");
    expect(agent).toContain("tools: 'Bash, Read'");
    expect(agent).toContain('opencode run --agent "MoKa Inspector"');

    const settings = JSON.parse(
      readFileSync(join(dir, ".claude/settings.json"), "utf8")
    );
    expect(settings.permissions.allow).toEqual([
      "Task",
      "Bash(opencode run *)",
    ]);
    expect(settings.mcpServers["pipeline-gateway"]).toMatchObject({
      type: "http",
      url: "https://pipeline-mcp.momokaya.ee/mcp/",
    });
  });

  it("is idempotent and check passes for Claude Code", async () => {
    await installCommands({ cwd: dir, host: "claude-code" });

    const second = await installCommands({ cwd: dir, host: "claude-code" });
    expect(second.items.every((item) => item.action === "unchanged")).toBe(
      true
    );

    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "claude-code",
    });
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("detects Claude Code drift on generated files via --check", async () => {
    await installCommands({ cwd: dir, host: "claude-code" });

    const path = join(dir, ".claude/commands/moka-execute.md");
    writeFileSync(
      path,
      [
        "<!-- Generated by @oisincoveney/pipeline. -->",
        "<!-- @oisincoveney/pipeline:host=claude-code -->",
        "",
        "drifted body",
        "",
      ].join("\n")
    );

    await expect(
      installCommands({ check: true, cwd: dir, host: "claude-code" })
    ).rejects.toThrow("not up to date");
  });

  it("protects manually edited Claude Code files unless forced", async () => {
    await installCommands({ cwd: dir, host: "claude-code" });

    const path = join(dir, ".claude/commands/moka-execute.md");
    writeFileSync(path, "manually edited");

    await expect(
      installCommands({ cwd: dir, host: "claude-code" })
    ).rejects.toThrow("Refusing to overwrite");

    const forced = await installCommands({
      cwd: dir,
      force: true,
      host: "claude-code",
    });
    expect(
      forced.items.find(
        (item) => item.path === ".claude/commands/moka-execute.md"
      )?.action
    ).toBe("update");
    expect(readFileSync(path, "utf8")).toContain(
      "Generated by @oisincoveney/pipeline"
    );
  });

  it("merges Claude settings without clobbering user-owned keys", async () => {
    const settingsPath = join(dir, ".claude/settings.json");
    mkdirSync(join(dir, ".claude"), { recursive: true });
    writeFileSync(
      settingsPath,
      `${JSON.stringify(
        {
          model: "opus",
          permissions: { allow: ["Read"], deny: ["Bash(rm *)"] },
          mcpServers: { custom: { type: "stdio", command: "x" } },
        },
        null,
        2
      )}\n`
    );

    await installCommands({ cwd: dir, force: true, host: "claude-code" });

    const settings = JSON.parse(readFileSync(settingsPath, "utf8"));
    // User-owned keys preserved.
    expect(settings.model).toBe("opus");
    expect(settings.permissions.deny).toEqual(["Bash(rm *)"]);
    expect(settings.mcpServers.custom).toMatchObject({ command: "x" });
    // Generated keys injected: allow is unioned, gateway server added.
    expect(settings.permissions.allow).toEqual([
      "Read",
      "Task",
      "Bash(opencode run *)",
    ]);
    expect(settings.mcpServers["pipeline-gateway"]).toMatchObject({
      type: "http",
    });

    // Idempotent: a second install reports no change to the merged settings.
    const second = await installCommands({
      cwd: dir,
      force: true,
      host: "claude-code",
    });
    expect(
      second.items.find((item) => item.path === ".claude/settings.json")?.action
    ).toBe("unchanged");
  });
});
