import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { installCommands, parseCommandHost } from "../src/install-commands.js";

const CODEX_SKILL_FRONTMATTER_RE =
  /^---\n[\s\S]*?name: pipe\n---\n<!-- Generated by @oisincoveney\/pipeline\. -->/;
const COMMAND_FRONTMATTER_RE =
  /^---\n[\s\S]*?description: [\s\S]*?\n---\n<!-- Generated by @oisincoveney\/pipeline\. -->/;

const ENTRYPOINT_COMMAND_SURFACES = [
  ".opencode/commands/pipe.md",
  ".opencode/commands/inspect.md",
  ".agents/skills/pipe/SKILL.md",
  ".agents/skills/inspect/SKILL.md",
  ".agents/plugins/oisin-pipeline/commands/pipe.md",
  ".agents/plugins/oisin-pipeline/commands/inspect.md",
];

describe("installCommands", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "pipeline-commands-"));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("installs command adapters from package config without repo pipeline files", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(existsSync(join(dir, ".pipeline"))).toBe(false);
    expect(result.items.map((item) => item.path)).toContain(
      ".agents/skills/pipe/SKILL.md"
    );
    expect(result.items.map((item) => item.path)).toContain(
      ".agents/skills/epic/SKILL.md"
    );
    expect(existsSync(join(dir, ".agents/skills/pipe/SKILL.md"))).toBe(true);
    expect(existsSync(join(dir, ".opencode/commands/epic.md"))).toBe(true);
  });

  it("installs all generated host resources from package defaults", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(result.items.every((item) => item.action === "create")).toBe(true);
    expect(result.items.map((item) => item.path)).toEqual([
      ".opencode/commands/pipe.md",
      ".opencode/commands/inspect.md",
      ".opencode/commands/epic.md",
      ".opencode/opencode.json",
      ".opencode/agents/pipeline-orchestrator.md",
      ".opencode/agents/pipeline-acceptance-reviewer.md",
      ".opencode/agents/pipeline-code-writer.md",
      ".opencode/agents/pipeline-epic-router.md",
      ".opencode/agents/pipeline-inspector.md",
      ".opencode/agents/pipeline-learner.md",
      ".opencode/agents/pipeline-researcher.md",
      ".opencode/agents/pipeline-test-writer.md",
      ".opencode/agents/pipeline-thermo-nuclear-reviewer.md",
      ".opencode/agents/pipeline-verifier.md",
      ".agents/skills/pipe/SKILL.md",
      ".agents/skills/inspect/SKILL.md",
      ".agents/skills/epic/SKILL.md",
      ".agents/plugins/oisin-pipeline/commands/pipe.md",
      ".agents/plugins/oisin-pipeline/commands/inspect.md",
      ".agents/plugins/oisin-pipeline/commands/epic.md",
      "AGENTS.md",
      ".codex/agents/pipeline-acceptance-reviewer.toml",
      ".codex/agents/pipeline-code-writer.toml",
      ".codex/agents/pipeline-epic-router.toml",
      ".codex/agents/pipeline-inspector.toml",
      ".codex/agents/pipeline-learner.toml",
      ".codex/agents/pipeline-researcher.toml",
      ".codex/agents/pipeline-test-writer.toml",
      ".codex/agents/pipeline-thermo-nuclear-reviewer.toml",
      ".codex/agents/pipeline-verifier.toml",
      ".codex/config.toml",
    ]);
    for (const item of result.items) {
      expect(existsSync(join(dir, item.path))).toBe(true);
    }
    expect(
      readFileSync(join(dir, ".agents/skills/pipe/SKILL.md"), "utf8")
    ).toMatch(CODEX_SKILL_FRONTMATTER_RE);
    expect(
      readFileSync(join(dir, ".opencode/commands/pipe.md"), "utf8")
    ).toMatch(COMMAND_FRONTMATTER_RE);
  });

  it("installs the pipeline gateway project config for Codex and OpenCode together", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(result.items).toContainEqual(
      expect.objectContaining({
        action: "create",
        host: "codex",
        path: ".codex/config.toml",
      })
    );
    expect(result.items).toContainEqual(
      expect.objectContaining({
        action: "create",
        host: "opencode",
        path: ".opencode/opencode.json",
      })
    );

    const codex = readFileSync(join(dir, ".codex/config.toml"), "utf8");
    expect(codex).toContain("[mcp_servers.pipeline-gateway]");
    expect(codex).toContain('url = "http://127.0.0.1:4483/mcp"');
    expect(codex).toContain("[mcp_servers.pipeline-gateway.env_http_headers]");
    expect(codex).toContain(
      'Authorization = "PIPELINE_MCP_GATEWAY_AUTHORIZATION"'
    );

    const opencode = JSON.parse(
      readFileSync(join(dir, ".opencode/opencode.json"), "utf8")
    );
    expect(opencode.mcp["pipeline-gateway"]).toMatchObject({
      enabled: true,
      oauth: false,
      type: "remote",
      url: "http://127.0.0.1:4483/mcp",
    });
    expect(opencode.mcp["pipeline-gateway"].headers).toEqual({
      Authorization: "{env:PIPELINE_MCP_GATEWAY_AUTHORIZATION}",
    });
  });

  it("renders scheduled entrypoints as CLI schedule generation instructions", async () => {
    await installCommands({ cwd: dir, host: "all" });

    for (const path of [
      ".agents/skills/pipe/SKILL.md",
      ".agents/skills/epic/SKILL.md",
      ".opencode/commands/pipe.md",
      ".opencode/commands/epic.md",
    ]) {
      const content = readFileSync(join(dir, path), "utf8");
      expect(content).toContain("Generate a schedule for entrypoint");
      expect(content).toContain(
        "The pipeline CLI runtime is the deterministic graph scheduler"
      );
      expect(content).toContain(
        "Use `pipe run --schedule <schedule.yaml>` only when rerunning"
      );
    }
  });

  it("generates a managed AGENTS.md block with repo-scoped pipeline memory guidance", async () => {
    await installCommands({ cwd: dir, host: "codex" });

    const content = readFileSync(join(dir, "AGENTS.md"), "utf8");
    expect(content).toContain("<!-- @oisincoveney/pipeline:agents:start -->");
    expect(content).toContain("<!-- @oisincoveney/pipeline:agents:end -->");
    expect(content).toContain(
      "This repository uses package-owned `@oisincoveney/pipeline` config."
    );
    expect(content).toContain("Use `$pipe`, `$inspect`, or `$epic`");
    expect(content).toContain("Use `/pipe`, `/inspect`, or `/epic`");
    expect(content).toContain("Call `qdrant-find` before research");
    expect(content).toContain("Call `qdrant-store` during LEARN");
    expect(content).toContain(`collection_name: ${basename(dir)}`);
    expect(content).toContain("metadata");
    expect(content).toContain("repo");
    expect(content).toContain("phase");
    expect(content).toContain("outcome");
  });

  it("updates only the managed AGENTS.md block and preserves project-authored instructions", async () => {
    writeFileSync(
      join(dir, "AGENTS.md"),
      ["# Project rules", "", "- Keep this custom rule.", ""].join("\n")
    );

    await installCommands({ cwd: dir, host: "codex" });
    const first = readFileSync(join(dir, "AGENTS.md"), "utf8");

    expect(first).toContain("# Project rules");
    expect(first).toContain("- Keep this custom rule.");
    expect(first).toContain("<!-- @oisincoveney/pipeline:agents:start -->");

    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "codex",
    });
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("is idempotent and check passes after install", async () => {
    await installCommands({ cwd: dir, host: "all" });

    const second = await installCommands({ cwd: dir, host: "all" });
    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "all",
    });

    expect(second.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("dry-run reports creates for entrypoint command surfaces without writing files", async () => {
    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "all",
    });

    for (const path of ENTRYPOINT_COMMAND_SURFACES) {
      expect(result.items).toContainEqual(
        expect.objectContaining({ action: "create", path })
      );
      expect(existsSync(join(dir, path))).toBe(false);
    }
    expect(existsSync(join(dir, ".pipeline"))).toBe(false);
  });

  it("check fails when commands are missing", async () => {
    await expect(
      installCommands({ check: true, cwd: dir, host: "opencode" })
    ).rejects.toThrow("not up to date");
  });

  it("dry-run reports conflicts without throwing or overwriting", async () => {
    const path = join(dir, ".opencode/commands/pipe.md");
    mkdirSync(join(dir, ".opencode/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "opencode",
    });

    expect(result.items[0]).toMatchObject({
      action: "conflict",
      host: "opencode",
      path: ".opencode/commands/pipe.md",
    });
    expect(readFileSync(path, "utf8")).toBe("manual command");
  });

  it("refuses to overwrite manually edited files unless forced", async () => {
    const path = join(dir, ".opencode/commands/pipe.md");
    mkdirSync(join(dir, ".opencode/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    await expect(
      installCommands({ cwd: dir, host: "opencode" })
    ).rejects.toThrow("Refusing to overwrite");

    const forced = await installCommands({
      cwd: dir,
      force: true,
      host: "opencode",
    });

    expect(forced.items[0]).toMatchObject({
      action: "update",
      host: "opencode",
      path: ".opencode/commands/pipe.md",
    });
    expect(readFileSync(path, "utf8")).toContain(
      "Generated by @oisincoveney/pipeline"
    );
  });

  it("validates host names through Commander parser hook", () => {
    expect(parseCommandHost("all")).toBe("all");
    expect(parseCommandHost("codex")).toBe("codex");
    expect(parseCommandHost("opencode")).toBe("opencode");
    expect(() => parseCommandHost("bad")).toThrow('Unsupported host "bad"');
  });
});
