import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { installCommands, parseCommandHost } from "../src/install-commands";

const COMMAND_FRONTMATTER_RE =
  /^---\n[\s\S]*?description: [\s\S]*?\n---\n<!-- Generated by @oisincoveney\/pipeline\. -->/;

const ENTRYPOINT_COMMAND_SURFACES = [
  ".opencode/commands/quick.md",
  ".opencode/commands/execute.md",
  ".opencode/commands/inspect.md",
];

describe("installCommands", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "pipeline-commands-"));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("installs command adapters from package config without repo pipeline files", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(existsSync(join(dir, ".pipeline"))).toBe(false);
    expect(result.items.map((item) => item.path)).toContain(
      ".opencode/commands/execute.md"
    );
    expect(result.items.map((item) => item.path)).toContain(
      ".opencode/commands/quick.md"
    );
    expect(existsSync(join(dir, ".agents/skills/execute/SKILL.md"))).toBe(
      false
    );
    expect(existsSync(join(dir, ".opencode/commands/quick.md"))).toBe(true);
    expect(existsSync(join(dir, ".opencode/commands/pipe.md"))).toBe(false);
    expect(existsSync(join(dir, ".opencode/commands/epic.md"))).toBe(false);
  });

  it("installs all generated host resources from package defaults", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(result.items.every((item) => item.action === "create")).toBe(true);
    expect(result.items.map((item) => item.path)).toEqual([
      ".opencode/commands/quick.md",
      ".opencode/commands/execute.md",
      ".opencode/commands/inspect.md",
      ".opencode/opencode.json",
      ".opencode/agents/pipeline-orchestrator.md",
      ".opencode/agents/pipeline-inspector.md",
      ".opencode/skills/critique/SKILL.md",
      ".opencode/skills/doubt/SKILL.md",
      ".opencode/skills/fix/SKILL.md",
      ".opencode/skills/library-first-development/SKILL.md",
      ".opencode/skills/migrate/SKILL.md",
      ".opencode/skills/optimize/SKILL.md",
      ".opencode/skills/research/SKILL.md",
      ".opencode/skills/schedule-graph-shaping/SKILL.md",
      ".opencode/skills/scope/SKILL.md",
      ".opencode/skills/secure/SKILL.md",
      ".opencode/skills/spec/SKILL.md",
      ".opencode/skills/test/SKILL.md",
      ".opencode/skills/trace/SKILL.md",
      ".opencode/skills/verify/SKILL.md",
      ".opencode/plugins/pipeline-goal-context.ts",
      "AGENTS.md",
    ]);
    for (const item of result.items) {
      expect(existsSync(join(dir, item.path))).toBe(true);
    }
    expect(
      readFileSync(join(dir, ".opencode/commands/execute.md"), "utf8")
    ).toMatch(COMMAND_FRONTMATTER_RE);
    const opencode = JSON.parse(
      readFileSync(join(dir, ".opencode/opencode.json"), "utf8")
    );
    expect(opencode.lsp).toBe(true);
    expect(opencode.plugin).toEqual([
      "@devtheops/opencode-plugin-otel@1.1.0",
      "@prevalentware/opencode-goal-plugin",
      "oc-codex-multi-auth",
    ]);
    const orchestrator = readFileSync(
      join(dir, ".opencode/agents/pipeline-orchestrator.md"),
      "utf8"
    );
    expect(orchestrator).toContain("mode: primary");
    expect(orchestrator).toContain("task:");
    expect(orchestrator).toContain("pipeline-inspector: allow");
    const inspector = readFileSync(
      join(dir, ".opencode/agents/pipeline-inspector.md"),
      "utf8"
    );
    expect(inspector).toContain("mode: subagent");
    expect(inspector).toContain("hidden: false");
    expect(inspector).toContain("skill:");
    expect(inspector).toContain("research: allow");
    expect(inspector).toContain("task: deny");
    const projectedSkill = readFileSync(
      join(dir, ".opencode/skills/library-first-development/SKILL.md"),
      "utf8"
    );
    expect(projectedSkill).toContain("name: library-first-development");
    expect(projectedSkill).toContain("compatibility: opencode");
    expect(projectedSkill).toContain(
      "Canonical source: `.agents/skills/library-first-development/SKILL.md`."
    );
    const localPlugin = readFileSync(
      join(dir, ".opencode/plugins/pipeline-goal-context.ts"),
      "utf8"
    );
    expect(localPlugin).toContain("Generated by @oisincoveney/pipeline.");
    expect(localPlugin).toContain("@oisincoveney/pipeline:host=opencode");
    expect(localPlugin).toContain("PipelineGoalContext");
    expect(localPlugin).toContain("experimental.session.compacting");
    expect(orchestrator).toContain(
      "Generate a schedule for entrypoint `quick`"
    );
    expect(orchestrator).toContain(
      "Run `moka submit --quick <task description>`"
    );
    expect(orchestrator).toContain(
      "Use `--kubeconfig <path>` and `--namespace <namespace>` to target a local or remote Kubernetes cluster."
    );
    expect(orchestrator).toContain(
      "Generate a schedule for entrypoint `execute`"
    );
    expect(orchestrator).not.toContain(
      "Run workflow `inspect` for the user task."
    );
  });

  it("installs the pipeline gateway project config for OpenCode", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(result.items).toContainEqual(
      expect.objectContaining({
        action: "create",
        host: "opencode",
        path: ".opencode/opencode.json",
      })
    );

    const opencode = JSON.parse(
      readFileSync(join(dir, ".opencode/opencode.json"), "utf8")
    );
    expect(opencode.mcp["pipeline-gateway"]).toMatchObject({
      enabled: true,
      oauth: false,
      type: "remote",
      url: "https://pipeline-mcp.momokaya.ee/mcp/",
    });
    expect(opencode.mcp["pipeline-gateway"].headers).toEqual({
      Authorization: "{env:PIPELINE_MCP_GATEWAY_AUTHORIZATION}",
    });
  });

  it("renders scheduled entrypoints as CLI schedule generation instructions", async () => {
    await installCommands({ cwd: dir, host: "all" });

    for (const path of [
      ".opencode/commands/quick.md",
      ".opencode/commands/execute.md",
    ]) {
      const content = readFileSync(join(dir, path), "utf8");
      expect(content).toContain("Generate a schedule for entrypoint");
      expect(content).toContain(
        "Submit Momokaya work as Argo Workflows through `moka submit` and `moka submit --quick`"
      );
      expect(content).toContain("Use `moka submit ");
      expect(content).toContain("--kubeconfig <path>");
      expect(content).not.toContain("--local <task description>");
    }
  });

  it("generates a managed AGENTS.md block with repo-scoped pipeline memory guidance", async () => {
    await installCommands({ cwd: dir, host: "opencode" });

    const content = readFileSync(join(dir, "AGENTS.md"), "utf8");
    expect(content).toContain("<!-- @oisincoveney/pipeline:agents:start -->");
    expect(content).toContain("<!-- @oisincoveney/pipeline:agents:end -->");
    expect(content).toContain(
      "This repository uses package-owned `@oisincoveney/pipeline` config."
    );
    expect(content).toContain("Use `/quick`, `/execute`, or `/inspect`");
    expect(content).toContain("Call `qdrant-find` before research");
    expect(content).toContain("Call `qdrant-store` during LEARN");
    expect(content).toContain(`collection_name: ${basename(dir)}`);
    expect(content).toContain("metadata");
    expect(content).toContain("repo");
    expect(content).toContain("phase");
    expect(content).toContain("outcome");
  });

  it("updates only the managed AGENTS.md block and preserves project-authored instructions", async () => {
    writeFileSync(
      join(dir, "AGENTS.md"),
      ["# Project rules", "", "- Keep this custom rule.", ""].join("\n")
    );

    await installCommands({ cwd: dir, host: "opencode" });
    const first = readFileSync(join(dir, "AGENTS.md"), "utf8");

    expect(first).toContain("# Project rules");
    expect(first).toContain("- Keep this custom rule.");
    expect(first).toContain("<!-- @oisincoveney/pipeline:agents:start -->");

    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "opencode",
    });
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("is idempotent and check passes after install", async () => {
    await installCommands({ cwd: dir, host: "all" });

    const second = await installCommands({ cwd: dir, host: "all" });
    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "all",
    });

    expect(second.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("dry-run reports creates for entrypoint command surfaces without writing files", async () => {
    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "all",
    });

    for (const path of ENTRYPOINT_COMMAND_SURFACES) {
      expect(result.items).toContainEqual(
        expect.objectContaining({ action: "create", path })
      );
      expect(existsSync(join(dir, path))).toBe(false);
    }
    expect(existsSync(join(dir, ".pipeline"))).toBe(false);
  });

  it("check fails when commands are missing", async () => {
    await expect(
      installCommands({ check: true, cwd: dir, host: "opencode" })
    ).rejects.toThrow("not up to date");
  });

  it("dry-run reports conflicts without throwing or overwriting", async () => {
    const path = join(dir, ".opencode/commands/quick.md");
    mkdirSync(join(dir, ".opencode/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "opencode",
    });

    expect(result.items[0]).toMatchObject({
      action: "conflict",
      host: "opencode",
      path: ".opencode/commands/quick.md",
    });
    expect(readFileSync(path, "utf8")).toBe("manual command");
  });

  it("refuses to overwrite manually edited files unless forced", async () => {
    const path = join(dir, ".opencode/commands/quick.md");
    mkdirSync(join(dir, ".opencode/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    await expect(
      installCommands({ cwd: dir, host: "opencode" })
    ).rejects.toThrow("Refusing to overwrite");

    const forced = await installCommands({
      cwd: dir,
      force: true,
      host: "opencode",
    });

    expect(forced.items[0]).toMatchObject({
      action: "update",
      host: "opencode",
      path: ".opencode/commands/quick.md",
    });
    expect(readFileSync(path, "utf8")).toContain(
      "Generated by @oisincoveney/pipeline"
    );
  });

  it("validates host names through Commander parser hook", () => {
    expect(parseCommandHost("all")).toBe("all");
    expect(parseCommandHost("opencode")).toBe("opencode");
    expect(() => parseCommandHost("bad")).toThrow('Unsupported host "bad"');
  });
});
