---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: momokaya-pipeline
spec:
  encryptedData:
    .dockerconfigjson: AgB6nVa++H/K3U5to1Ukfztxjn796cMFnASMqUCazxrZD4wKkbLKq9JabgnY+qyYboTZHKp2jfPW0KnL9bhb/XVYsgUJ/1ly5SDg9b8gjzI/2HLWmgzSh7thIGjNqgtOKPVCkGKZQ+FliEvBuzI1AIAl/fvuOXTh+WE5CHHYkOCV1Su7VyiO+Cu/czJ241CQbaM9N4+hSgmIzphWjDr6lM7hLF/9e6RAFV6WqrLzkLlqTZh2QnPeIMBxVr+grSXM/lBTqICU3CDSqea6miGl1vwqrMQB9kEv5LvCknh20iYN/NXTVXmNH1g/ETW9CqdFzFELxpwcpzakl6zq4FflI7A1QnXkmurROTRB7UhX0znn5t5VuQ8dxq5MxyU6ryOWP3EQXeSfLrNXAwUaGsiyMVwDnNTKY9dbVGCNg3qQ8Tebxy5cVVmtRglbaBattsUkQT8vos+w+OLFHY6KSo+gbaQ/IY+3fIWonyYBllgPQdgMIk/iQD5CK3U1k25l5AGJrP6zYxpwNdZZ/nAXM0tn4Nw1iSal+yT5rN39ROssAhxqL1NBfVXOXleDr9TZXDdAs8CvkP5mkFETOKRhfpAiEf0lXJuWXu3OW7ABZAnYFykqQdbErVvbK5jSRz89H3R/ICn7KOpqB3wf+bdhKXuZ4iyOLA0rh7pj+oebbU93GAI0CkJDjLj3ui+DQwdBGUfCPDaK217zVKMfvTW5Rn4TZPZPVuKFFmrFk6lWzZxFVFyXT/i6JLUnBDRxrmjOmDpiZDLcQ+q7Q6asfuD17ly8i/KIT/hA/isQVtanxZIb6f8pWU4aLtgaoVW6vva9LQHIovioc54eRCXqNlT7CEPPnIopv1J5IkZIoi67ccOR+50P9AFSDEdydBTlNjBWv/sfTAypKfi+nf47sZShtr2QbShC9DkDJASVVzGXSuvOQaIujSKz
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: momokaya-pipeline
    type: kubernetes.io/dockerconfigjson
