---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oisin-bot-git-credentials
  namespace: momokaya-pipeline
spec:
  encryptedData:
    password: AgAfMqauIGydScBGrjfy0j+W4QakFYACFJYJKvifv/4jtPSIPUd6ih1kslfcANQ+YHOJVisTanVJUNmaYuWohK/LPlIa8p7B/wMTcWCeXbRKN7IdceSkQy1UonHKDkK3gKv1gGGXUYFaA8pSyoS2zZ6DYdr7kori8gTe0EU4JT93BCXL3MP4DXf/0FIvk5U0EWrbkNMvKHIav7r0qMFVUTJIMN2Dh7i47VBglHvjtdgLxAKK3Gclbs8ewGpzlOgOQ8b7P3GWy2lkncRJKwxRKKN4j+fBgUIr54neMmK8aJFDWmcLu0/6a1yq0Pmm4JXU6WYWW1NdEvj0PXXtWkzlZ/pzow5pfq3MTlze5VxF+03/YxV6nyA47HRZa9m3QIkRpoN2PW5mnmNMZn16VoQV7dFUYuHMWf6tqF5bIge4N44RaF4xWjep0Q40pWVxpCHm1EoRkqa4/gOga37oEi0xObhauDyFBSv6KzlcKk2p27SvN4eRMqXTomAlpjhPqD/ywAJkAonHvq/lx5zHNT2VdUuv2IZIaJCxxiPxg/mBSGDq/K7MdVTIfk35OEFTEQ1+HlHKZjLoq1Vvwg/kY+/15rGdYaPXVZt63WSNA9Z5bkq2l43KzgGKximqPoeQjEXQYlf1uPZg4seGoaV12ELXMLgsmSmwxHsCKxKTVXJa/ZODynn5wdcx2OqXTeT2DaMIQR80bPqlDxs9zMNk4mnYrqnIXnfrzpII7hs75kk9J6Pv02/HFhNM3fPB
    username: AgBkWDV+amA95GcEAVI6rhu+dRyMw+VTbcoNxEvXKmuCyVaSSIgKIzh6yGQiOdHrTl9iBRhadZMs7h8q3GB6hBdNIQc2cPMBrIWshQEj5eYETSlNOW/L4UL+KLPUQAcC8kzrpnXWk4NPEOASZLbCh80njUDEpfIzFyFH1LGRH0nUTT8Et7J3v+hxTZxOp2Hmp19LT6aeZ8j3J1vX184H5JaL1vyKOaXhBQPUW0mOXVfgQpRjiiLlwIojarQMm2an/88y24+M7JWZC8C6v/2e+PQrYZFvNtc4n97sL4m9T//fOrLMJ+7HR1ej+6nJnkZQ8AqRPE3kGLlUDWKbcwXG1/9/cxv74alyFsJvzXjrohhs3cqj5D1UNJlMQ8KKjlfBfGQ1pbti1uBGtlLBdMaa25sTtomwt+7oZTG46vJq7jgCwHpq7f6p5WNjoUjI18o3vNgTXG3gTaftRoCTZiffcJY5pfqLnkik/z21G5/XDna6PW7RiLrwLNpRxhn6RHUr4dHdkaKYkDGl49L+Vl0E8QpK0/9RGf2e6pOSrGY9chIBsfaOTtN/wgt9rEg8bXCK5aAfFG0PKeLqzBeVUpo9++tAtrG1XJqJBCzSCr1ndb0eHohoxPAW/NCzoKa8+bHAGoWduBUiO98bZWwxsHv3nQEW7fQLR/U7p3j9HQ1UYEQcuyi60SA3jIxhQnQxiRmU+GySVoJCKqKzC48=
  template:
    metadata:
      name: oisin-bot-git-credentials
      namespace: momokaya-pipeline
