import { existsSync, readFileSync, statSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative } from "node:path";
import matter from "gray-matter";
import {
  DEFAULT_OPENCODE_ECOSYSTEM_MANIFEST,
  loadPipelineConfig,
  type OpenCodeEcosystemManifest,
  type PipelineConfig,
} from "./config";
import { renderOpenCodeGatewayConfig } from "./mcp/gateway";
import { mergeOpenCodeProjectConfig } from "./opencode-project-config";
import { resolvePackageAssetPath } from "./package-assets";
import { resolveFileReference } from "./path-refs";
import { compileWorkflowPlan } from "./workflow-planner";

const GENERATED_MARKER = "<!-- Generated by @oisincoveney/pipeline. -->";
const GENERATED_TS_MARKER = "// Generated by @oisincoveney/pipeline.";
const GENERATED_YAML_MARKER = "# Generated by @oisincoveney/pipeline.";
const OWNER_MARKER_PREFIX = "<!-- @oisincoveney/pipeline:";
const OWNER_TS_MARKER_PREFIX = "// @oisincoveney/pipeline:";
const OWNER_YAML_MARKER_PREFIX = "# @oisincoveney/pipeline:";
const AGENTS_MD_START = "<!-- @oisincoveney/pipeline:agents:start -->";
const AGENTS_MD_END = "<!-- @oisincoveney/pipeline:agents:end -->";
const SINGLE_OPENCODE_PLUGIN_ARRAY_RE =
  /\n {2}"plugin": \[\n {4}("[^"]+")\n {2}\]/;
const OPENCODE_PROJECT_CONFIG_PATH = ".opencode/opencode.json";
const ENTRYPOINT_PATH_PATTERNS: Record<ActiveCommandHost, RegExp[]> = {
  opencode: [/^\.opencode\/commands\/([^/]+)\.md$/],
};
const COMMAND_HOSTS = ["opencode"] as const;

type ActiveCommandHost = (typeof COMMAND_HOSTS)[number];
export type CommandHostSelection = ActiveCommandHost | "all";
export type InstallAction =
  | "conflict"
  | "create"
  | "delete"
  | "unchanged"
  | "update";

export interface CommandInstallPlanItem {
  action: InstallAction;
  host: ActiveCommandHost;
  invocation: string;
  path: string;
}

export interface InstallCommandsOptions {
  check?: boolean;
  cwd?: string;
  dryRun?: boolean;
  force?: boolean;
  host?: CommandHostSelection;
}

export interface InstallCommandsResult {
  items: CommandInstallPlanItem[];
}

interface InstallCommandsContext {
  cwd: string;
  definitions: CommandDefinition[];
  host: CommandHostSelection;
  wantedPaths: Set<string>;
}

interface CommandDefinition {
  block?: {
    end: string;
    start: string;
  };
  content: string;
  host: ActiveCommandHost;
  invocation: string;
  path: string;
}

type EntrypointEntry = [string, PipelineConfig["entrypoints"][string]];
type ProfileEntry = [string, PipelineConfig["profiles"][string]];
type ActorConfig = PipelineConfig["profiles"][string];

const OPENCODE_ORCHESTRATOR_AGENT_ID = "MoKa Orchestrator";
const MOKA_PROFILE_PREFIX = "moka-";
type EcosystemCode = OpenCodeEcosystemManifest["ecosystem_code"][number];

interface OpencodePermissionOptions {
  allowedTaskAgents?: string[];
}

type DispatchKind = "cli" | "native-model-agent" | "native-named-agent";

interface AgentDispatchRoute {
  kind: DispatchKind;
  model?: string;
  nativeAgentId?: string;
  needs: string[];
  nodeId: string;
  profile: PipelineConfig["profiles"][string];
  profileId: string;
  runnerId: string;
}

function header(host: ActiveCommandHost): string {
  return [GENERATED_MARKER, `${OWNER_MARKER_PREFIX}host=${host} -->`, ""].join(
    "\n"
  );
}

function markdown(data: Record<string, unknown>, body: string): string {
  return `${matter.stringify(body.trimEnd(), data).trimEnd()}\n`;
}

function profileEntries(config: PipelineConfig): ProfileEntry[] {
  return Object.entries(config.profiles).sort(([a], [b]) => a.localeCompare(b));
}

function entrypointEntries(config: PipelineConfig): EntrypointEntry[] {
  const entries = Object.entries(config.entrypoints);
  return entries.length > 0
    ? entries
    : [
        [
          "execute",
          {
            description: "Run the configured pipeline workflow",
            workflow: config.default_workflow,
          },
        ],
      ];
}

function entrypointDescription(
  id: string,
  entrypoint: PipelineConfig["entrypoints"][string]
): string {
  return entrypoint.description ?? `Run the ${id} workflow`;
}

function entrypointCommandDefinitions(
  _host: ActiveCommandHost,
  config: PipelineConfig,
  makeDefinition: (
    id: string,
    entrypoint: PipelineConfig["entrypoints"][string]
  ) => CommandDefinition
): CommandDefinition[] {
  return entrypointEntries(config).map(([id, entrypoint]) =>
    makeDefinition(id, entrypoint)
  );
}

function nativeProfileEntries(
  host: ActiveCommandHost,
  config: PipelineConfig
): ProfileEntry[] {
  return profileEntries(config).filter(
    ([id, profile]) =>
      id !== config.orchestrator?.profile && canRunNatively(host, profile)
  );
}

function orchestratorProfile(config: PipelineConfig): ActorConfig | undefined {
  if (!config.orchestrator) {
    return;
  }
  const profile = config.profiles[config.orchestrator.profile];
  if (!profile) {
    throw new Error(
      `Orchestrator profile '${config.orchestrator.profile}' is not declared.`
    );
  }
  return {
    ...profile,
  };
}

function resolvedHostModel(
  config: PipelineConfig,
  host: ActiveCommandHost,
  profile: PipelineConfig["profiles"][string]
): string | undefined {
  const runner = config.runners[profile.runner];
  const hostRunner = config.runners[host];
  if (profile.host_models?.[host]) {
    return profile.host_models[host];
  }
  if (runner?.host_models?.[host]) {
    return runner.host_models[host];
  }
  if (profile.runner === host) {
    return profile.model ?? runner?.model;
  }
  return hostRunner?.model;
}

function canRunNatively(
  host: ActiveCommandHost,
  profile: PipelineConfig["profiles"][string]
): boolean {
  if (profile.runner === host) {
    return true;
  }
  return host === "opencode" && isModelRunner(profile.runner);
}

function isModelRunner(runnerId: string): boolean {
  return COMMAND_HOSTS.some((host) => host === runnerId);
}

function agentDispatchRoutes(
  host: ActiveCommandHost,
  config: PipelineConfig,
  workflowId = config.default_workflow
): AgentDispatchRoute[] {
  const plan = compileWorkflowPlan(config, workflowId);
  return plan.topologicalOrder.flatMap((node) => {
    if (!(node.kind === "agent" && node.profile)) {
      return [];
    }
    const profile = config.profiles[node.profile];
    if (!profile) {
      return [];
    }
    return [
      dispatchRouteForAgent(host, config, {
        needs: node.needs,
        nodeId: node.id,
        profile,
        profileId: node.profile,
      }),
    ];
  });
}

function dispatchRouteForAgent(
  host: ActiveCommandHost,
  config: PipelineConfig,
  route: Pick<AgentDispatchRoute, "needs" | "nodeId" | "profile" | "profileId">
): AgentDispatchRoute {
  const runnerId = route.profile.runner;
  if (runnerId === host) {
    const model = resolvedHostModel(config, host, route.profile);
    return {
      ...route,
      kind: "native-named-agent",
      ...(model ? { model } : {}),
      nativeAgentId: nativeAgentIdForHost(host, route.profileId),
      runnerId,
    };
  }
  if (host === "opencode" && isModelRunner(runnerId)) {
    const model = resolvedHostModel(config, host, route.profile);
    return {
      ...route,
      kind: "native-model-agent",
      ...(model ? { model } : {}),
      nativeAgentId: nativeAgentIdForHost(host, route.profileId),
      runnerId,
    };
  }
  return {
    ...route,
    kind: "cli",
    runnerId,
  };
}

function nativeAgentIdForHost(host: ActiveCommandHost, profileId: string): string {
  return host === "opencode" ? opencodeAgentName(profileId) : profileId;
}

function opencodeAgentName(profileId: string): string {
  if (!profileId.startsWith(MOKA_PROFILE_PREFIX)) {
    return profileId;
  }
  const displayName = profileId
    .slice(MOKA_PROFILE_PREFIX.length)
    .split("-")
    .map(opencodeAgentNamePart)
    .join(" ");
  return `MoKa ${displayName}`;
}

function opencodeAgentNamePart(part: string): string {
  if (part === "opencode") {
    return "OpenCode";
  }
  return `${part.charAt(0).toUpperCase()}${part.slice(1)}`;
}

function grants(actor: ActorConfig): string {
  return [
    `model: ${actor.model ?? "default"}`,
    `tools: ${(actor.tools ?? []).join(", ") || "none"}`,
    `rules: ${(actor.rules ?? []).join(", ") || "none"}`,
    `skills: ${(actor.skills ?? []).join(", ") || "none"}`,
    `mcp_servers: ${(actor.mcp_servers ?? []).join(", ") || "none"}`,
    `filesystem: ${actor.filesystem?.mode ?? "default"}`,
    `network: ${actor.network?.mode ?? "default"}`,
    ...("output" in actor ? [`output: ${actor.output?.format ?? "text"}`] : []),
  ].join("\n");
}

function orchestratorBlock(config: PipelineConfig): string {
  const profile = orchestratorProfile(config);
  if (!profile) {
    return "Configured orchestrator: none";
  }
  return [
    "Configured orchestrator:",
    grants(profile),
    `hooks: ${Object.keys(config.hooks.functions).join(", ") || "none"}`,
    "",
    instructionsPointer(profile),
  ].join("\n");
}

function dispatchBlock(
  host: ActiveCommandHost,
  config: PipelineConfig,
  workflowId = config.default_workflow
): string | undefined {
  const routes = agentDispatchRoutes(host, config, workflowId);
  if (routes.length === 0) {
    return;
  }
  const plan = compileWorkflowPlan(config, workflowId);
  const nativeRoutes = routes.filter((route) => route.kind !== "cli");
  const cliRoutes = routes.filter((route) => route.kind === "cli");
  return [
    `Run workflow \`${plan.workflowId}\` for the user task.`,
    "",
    nativeDispatchBlock(host, nativeRoutes),
    cliDispatchBlock(host, cliRoutes),
    nodePromptContract(plan.workflowId, routes),
    "Only package-configured gates are blocking. Do not invent RED, GREEN, full-suite, typecheck, or unrelated-drift gates.",
    "If a node returns targeted evidence and has no configured blocking gate, advance to the next node.",
    "Do not bypass configured runner subprocesses or package-configured gates when executing nodes.",
    hostSpecificDispatchGuard(host, nativeRoutes, cliRoutes),
  ]
    .filter((line): line is string => Boolean(line))
    .join("\n");
}

function entrypointDispatchBlock(
  host: ActiveCommandHost,
  config: PipelineConfig,
  id: string,
  entrypoint: PipelineConfig["entrypoints"][string]
): string | undefined {
  if ("workflow" in entrypoint) {
    return dispatchBlock(host, config, entrypoint.workflow);
  }
  return [
    `Generate a schedule for entrypoint \`${id}\` and the user task.`,
    `The schedule policy is \`${entrypoint.schedule}\`.`,
    id === "quick"
      ? "Run `moka submit --quick <task description>` to submit the graph as an Argo Workflow."
      : `Run \`moka submit <task description>\` to submit the \`${id}\` graph as an Argo Workflow.`,
    "The pipeline runtime executes as Argo DAG tasks using the package-owned runner image.",
    "Use `--kubeconfig <path>` and `--namespace <namespace>` to target a local or remote Kubernetes cluster.",
    "Use `moka submit --schedule <schedule.yaml> <task description>` only when rerunning an existing schedule artifact.",
  ].join("\n");
}

function scheduledEntrypointK8sNote(
  entrypoint: PipelineConfig["entrypoints"][string]
): string | undefined {
  if ("workflow" in entrypoint) {
    return;
  }
  return "Submit Momokaya work as Argo Workflows through `moka submit` and `moka submit --quick`.";
}

function orchestratorEntrypointDispatchBlock(
  host: ActiveCommandHost,
  config: PipelineConfig
): string | undefined {
  const scheduledEntrypoints = entrypointEntries(config).filter(
    ([, entrypoint]) => !("workflow" in entrypoint)
  );
  if (scheduledEntrypoints.length === 0) {
    return dispatchBlock(host, config);
  }
  return scheduledEntrypoints
    .map(([id, entrypoint]) =>
      entrypointDispatchBlock(host, config, id, entrypoint)
    )
    .filter((block): block is string => Boolean(block))
    .join("\n\n");
}

function nativeDispatchBlock(
  host: ActiveCommandHost,
  routes: AgentDispatchRoute[]
): string | undefined {
  if (routes.length === 0) {
    return;
  }
  return [
    `${hostDisplayName(host)} native routes:`,
    ...routes.map(nativeDispatchLine),
    "",
  ].join("\n");
}

function nativeDispatchLine(route: AgentDispatchRoute): string {
  const needs = needsSummary(route.needs);
  const model = route.model ? ` model=${route.model}` : "";
  return `- ${route.nodeId}: Task tool subagent_type=${route.nativeAgentId}${model} runner=${route.runnerId} needs=${needs}`;
}

function cliDispatchBlock(
  host: ActiveCommandHost,
  routes: AgentDispatchRoute[]
): string | undefined {
  if (routes.length === 0) {
    return;
  }
  const nativeNotice = `These nodes are not ${hostDisplayName(host)} native routes.`;
  return [nativeNotice, "CLI routes:", ...routes.map(cliDispatchLine), ""].join(
    "\n"
  );
}

function cliDispatchLine(route: AgentDispatchRoute): string {
  return `- ${route.nodeId}: ${route.runnerId} CLI profile=${route.profileId} command=\`${runnerCliCommand(route)}\` needs=${needsSummary(route.needs)}`;
}

function runnerCliCommand(route: AgentDispatchRoute): string {
  if (route.runnerId === "opencode") {
    return `opencode run --agent "${opencodeAgentName(route.profileId)}" --format json --dir <repo-root> <node prompt>`;
  }
  throw new Error(
    `runner '${route.runnerId}' cannot be represented as a supported native or CLI route`
  );
}

function nodePromptContract(
  workflowId: string,
  routes: AgentDispatchRoute[]
): string {
  const hasCliRoutes = routes.some((route) => route.kind === "cli");
  const lead = hasCliRoutes
    ? "For each CLI node prompt include:"
    : "For each native node prompt include:";
  return [
    lead,
    "- user task",
    `- workflow id: ${workflowId}`,
    "- node id",
    "- profile id",
    "- runner id",
    "- profile instructions reference",
    "- profile grants",
    "- dependency outputs",
    "",
  ].join("\n");
}

function hostSpecificDispatchGuard(
  host: ActiveCommandHost,
  nativeRoutes: AgentDispatchRoute[],
  cliRoutes: AgentDispatchRoute[]
): string | undefined {
  if (cliRoutes.length > 0 && nativeRoutes.length > 0) {
    return `Do not claim CLI routes are ${hostDisplayName(host)} native routes.`;
  }
  if (cliRoutes.length > 0 && nativeRoutes.length === 0) {
    return `Do not claim these nodes are ${hostDisplayName(host)} subagents.`;
  }
  return;
}

function hostDisplayName(host: ActiveCommandHost): string {
  const names: Record<ActiveCommandHost, string> = {
    opencode: "OpenCode",
  };
  return names[host];
}

function needsSummary(needs: string[]): string {
  return needs.length > 0 ? needs.join(",") : "none";
}

function compactLines(lines: Array<string | undefined>): string[] {
  return lines.filter((line): line is string => line !== undefined);
}

const OPENCODE_PERMISSION_TOOLS = [
  "bash",
  "edit",
  "glob",
  "grep",
  "list",
  "read",
  "write",
] as const;

function opencodePermission(
  actor: ActorConfig,
  options: OpencodePermissionOptions = {}
): Record<string, string | Record<string, string>> {
  const allowed = new Set(actor.tools ?? []);
  return {
    ...opencodeToolPermissions(allowed),
    external_directory: "deny",
    lsp: "allow",
    skill: opencodeSkillPermission(actor.skills ?? []),
    task: opencodeTaskPermission(allowed, options.allowedTaskAgents ?? []),
  };
}

function opencodeToolPermissions(
  allowed: Set<string>
): Record<(typeof OPENCODE_PERMISSION_TOOLS)[number], string> {
  return Object.fromEntries(
    OPENCODE_PERMISSION_TOOLS.map((tool) => [
      tool,
      allowed.has(tool) ? "allow" : "deny",
    ])
  ) as Record<(typeof OPENCODE_PERMISSION_TOOLS)[number], string>;
}

function opencodeSkillPermission(
  skills: string[]
): string | Record<string, string> {
  return namedOpencodePermissionMap(skills);
}

function opencodeTaskPermission(
  allowed: Set<string>,
  allowedTaskAgents: string[]
): string | Record<string, string> {
  return allowedTaskAgents.length > 0
    ? namedOpencodePermissionMap(allowedTaskAgents)
    : toolPermission(allowed, "task");
}

function namedOpencodePermissionMap(
  names: string[]
): string | Record<string, string> {
  return names.length > 0
    ? {
        "*": "deny",
        ...Object.fromEntries(names.map((name) => [name, "allow"])),
      }
    : "deny";
}

function toolPermission(allowed: Set<string>, tool: string): string {
  return allowed.has(tool) ? "allow" : "deny";
}

function renderOpenCodeProjectConfig(config: PipelineConfig): string {
  const base = config.mcp_gateway
    ? (JSON.parse(renderOpenCodeGatewayConfig(config)) as Record<
        string,
        unknown
      >)
    : { $schema: "https://opencode.ai/config.json" };
  return formatOpenCodeProjectJson({
    ...base,
    lsp: true,
    ...opencodePluginConfig(),
  });
}

function opencodePluginConfig(): { plugin?: string[] } {
  const plugins = DEFAULT_OPENCODE_ECOSYSTEM_MANIFEST.ecosystem_code
    .flatMap((item) => npmPluginPackage(item))
    .sort((a, b) => a.localeCompare(b));
  return plugins.length > 0 ? { plugin: plugins } : {};
}

function npmPluginPackage(item: EcosystemCode): string[] {
  if (item.plugin?.kind === "npm") {
    return [item.plugin.package];
  }
  return [];
}

function formatOpenCodeProjectJson(value: Record<string, unknown>): string {
  return `${JSON.stringify(value, null, 2).replace(
    SINGLE_OPENCODE_PLUGIN_ARRAY_RE,
    '\n  "plugin": [$1]'
  )}\n`;
}

function localPluginDefinitions(): CommandDefinition[] {
  return DEFAULT_OPENCODE_ECOSYSTEM_MANIFEST.ecosystem_code.flatMap((item) => {
    if (item.plugin?.kind !== "local") {
      return [];
    }
    const source = resolvePackageAssetPath(item.plugin.source_path);
    const plugin = readFileSync(source, "utf8").trimEnd();
    return [
      {
        content: [
          GENERATED_TS_MARKER,
          `${OWNER_TS_MARKER_PREFIX}host=opencode`,
          "",
          plugin,
          "",
        ].join("\n"),
        host: "opencode" as const,
        invocation: invocationForHost("opencode"),
        path: item.plugin.target_path,
      },
    ];
  });
}

interface PipelineSkillProjection {
  description: string;
  id: string;
  path: string;
}

function opencodeSkillProjections(
  config: PipelineConfig,
  cwd: string
): PipelineSkillProjection[] {
  return [...profileSkillIds(config)]
    .sort((a, b) => a.localeCompare(b))
    .map((id) => {
      const configured = config.skills[id];
      const path = configured?.path ?? `.agents/skills/${id}/SKILL.md`;
      return {
        description: skillDescription(cwd, configured, path, id),
        id,
        path,
      };
    });
}

function profileSkillIds(config: PipelineConfig): Set<string> {
  return new Set(
    Object.values(config.profiles).flatMap((profile) => profile.skills ?? [])
  );
}

function skillDescription(
  cwd: string,
  configured: PipelineConfig["skills"][string] | undefined,
  path: string,
  id: string
): string {
  const absolutePath =
    configured?.source_root === "package"
      ? resolvePackageAssetPath(path)
      : resolveFileReference(cwd, path);
  if (existsSync(absolutePath)) {
    const parsed = matter(readFileSync(absolutePath, "utf8"));
    if (typeof parsed.data.description === "string") {
      return parsed.data.description;
    }
  }
  return `Pipeline skill ${id} projected from ${path}.`;
}

function opencodeSkillDefinition(
  skill: PipelineSkillProjection
): CommandDefinition {
  return {
    content: markdown(
      {
        compatibility: "opencode",
        description: skill.description,
        metadata: {
          "pipeline-source": skill.path,
        },
        name: skill.id,
      },
      [
        header("opencode").trimEnd(),
        "",
        `This is the package-owned OpenCode projection for pipeline skill \`${skill.id}\`.`,
        "",
        `Canonical source: \`${skill.path}\`.`,
        "",
        "Load this skill when a generated pipeline agent grants it through `permission.skill`.",
      ].join("\n")
    ),
    host: "opencode" as const,
    invocation: invocationForHost("opencode"),
    path: `.opencode/skills/${skill.id}/SKILL.md`,
  };
}

function opencodeDefinitions(
  config: PipelineConfig,
  cwd: string
): CommandDefinition[] {
  const orchestrator = orchestratorProfile(config);
  return [
    ...entrypointCommandDefinitions("opencode", config, (id, entrypoint) => ({
      content: markdown(
        {
          ...(orchestrator ? { agent: OPENCODE_ORCHESTRATOR_AGENT_ID } : {}),
          description: entrypointDescription(id, entrypoint),
        },
        compactLines([
          header("opencode").trimEnd(),
          "",
          `Invoke this command with \`${invocationForHost("opencode", id)}\`.`,
          "",
          orchestratorBlock(config),
          "",
          scheduledEntrypointK8sNote(entrypoint),
          scheduledEntrypointK8sNote(entrypoint) ? "" : undefined,
          entrypointDispatchBlock("opencode", config, id, entrypoint),
        ]).join("\n")
      ),
      host: "opencode",
      invocation: invocationForHost("opencode", id),
      path: `.opencode/commands/${id}.md`,
    })),
    {
      content: renderOpenCodeProjectConfig(config),
      host: "opencode" as const,
      invocation: invocationForHost("opencode"),
      path: ".opencode/opencode.json",
    },
    ...(orchestrator
      ? [
          {
            content: markdown(
              {
                description:
                  "Orchestrate the configured pipeline and enforce gates.",
                mode: "primary",
                name: OPENCODE_ORCHESTRATOR_AGENT_ID,
                permission: opencodePermission(orchestrator, {
                  allowedTaskAgents: agentDispatchRoutes("opencode", config)
                    .filter((route) => route.kind !== "cli")
                    .map((route) => route.nativeAgentId)
                    .filter((id): id is string => Boolean(id)),
                }),
              },
              compactLines([
                header("opencode").trimEnd(),
                "",
                orchestratorBlock(config),
                "",
                orchestratorEntrypointDispatchBlock("opencode", config),
              ]).join("\n")
            ),
            host: "opencode" as const,
            invocation: invocationForHost("opencode"),
            path: `.opencode/agents/${OPENCODE_ORCHESTRATOR_AGENT_ID}.md`,
          },
        ]
      : []),
    ...nativeProfileEntries("opencode", config).map(([id, profile]) => ({
      content: markdown(
        {
          name: nativeAgentIdForHost("opencode", id),
          description: profile.description ?? id,
          hidden: false,
          mode: "subagent",
          ...opencodeModelProjection(config, profile),
          permission: opencodePermission(profile),
        },
        [
          header("opencode").trimEnd(),
          "",
          profile.description ?? id,
          "",
          "Configured grants:",
          grants(profile),
          "",
          instructionsPointer(profile),
        ].join("\n")
      ),
      host: "opencode" as const,
      invocation: invocationForHost("opencode"),
      path: `.opencode/agents/${nativeAgentIdForHost("opencode", id)}.md`,
    })),
    ...opencodeSkillProjections(config, cwd).map(opencodeSkillDefinition),
    ...localPluginDefinitions(),
    projectAgentsMdDefinition(cwd, "opencode"),
  ];
}

function projectAgentsMdDefinition(
  cwd: string,
  host: ActiveCommandHost
): CommandDefinition {
  const repoName = basename(cwd);
  return {
    block: {
      end: AGENTS_MD_END,
      start: AGENTS_MD_START,
    },
    content: [
      AGENTS_MD_START,
      GENERATED_MARKER,
      `${OWNER_MARKER_PREFIX}host=opencode -->`,
      "",
      "## Pipeline Guidance",
      "",
      "This repository uses package-owned `@oisincoveney/pipeline` config.",
      "",
      "- Use `/quick`, `/execute`, or `/inspect` for OpenCode slash-command entrypoints when available.",
      "- Load and follow the relevant skill from `.agents/skills` before doing specialized work.",
      "- Prefer the package-defined pipeline profiles and generated command surfaces over ad hoc subagent prompts.",
      "",
      "## Pipeline Memory",
      "",
      `Use Qdrant collection \`${repoName}\` for this repository.`,
      "",
      `- Call \`qdrant-find\` before research with \`collection_name: ${repoName}\` unless the user explicitly disables memory.`,
      `- Call \`qdrant-store\` during LEARN with \`collection_name: ${repoName}\` for durable lessons worth reusing.`,
      "- Include metadata with at least `repo`, `phase`, `workflow` or `entrypoint`, `task`, and `outcome` when storing lessons.",
      "",
      AGENTS_MD_END,
      "",
    ].join("\n"),
    host,
    invocation: invocationForHost(host),
    path: "AGENTS.md",
  };
}

function opencodeModelProjection(
  config: PipelineConfig,
  profile: PipelineConfig["profiles"][string]
): Record<string, string> {
  const model = resolvedHostModel(config, "opencode", profile);
  return model ? { model } : {};
}

function instructionsPointer(actor: ActorConfig): string {
  if (actor.instructions.path) {
    return `Instructions: ${actor.instructions.path}`;
  }
  return `Instructions:\n${actor.instructions.inline ?? ""}`;
}

function definitionsFor(
  host: CommandHostSelection,
  config: PipelineConfig,
  cwd: string
): CommandDefinition[] {
  const definitions: Record<ActiveCommandHost, () => CommandDefinition[]> = {
    opencode: () => opencodeDefinitions(config, cwd),
  };
  const hosts = host === "all" ? COMMAND_HOSTS : [host];
  const rawDefinitions = hosts.flatMap((name) => definitions[name]());
  return dedupeDefinitionsByPath(rawDefinitions);
}

function dedupeDefinitionsByPath(
  definitions: CommandDefinition[]
): CommandDefinition[] {
  const lastIndexes = new Map<string, number>();
  definitions.forEach((definition, index) => {
    lastIndexes.set(definition.path, index);
  });
  return definitions.filter(
    (definition, index) => lastIndexes.get(definition.path) === index
  );
}

function selectedHosts(host: CommandHostSelection): ActiveCommandHost[] {
  return host === "all" ? [...COMMAND_HOSTS] : [host];
}

const GENERATED_RESOURCE_ROOTS: Record<ActiveCommandHost, string[]> = {
  opencode: [
    ".opencode/commands",
    ".opencode/agents",
    ".opencode/skills",
    ".opencode/plugins",
  ],
};

async function listFiles(root: string): Promise<string[]> {
  if (!existsSync(root)) {
    return [];
  }
  if (statSync(root).isFile()) {
    return [root];
  }
  const entries = await readdir(root, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const path = join(root, entry.name);
      if (entry.isDirectory()) {
        return listFiles(path);
      }
      return [path];
    })
  );
  return files.flat();
}

function generatedHostFor(content: string): ActiveCommandHost | undefined {
  return COMMAND_HOSTS.find(
    (host) =>
      content.includes(`${OWNER_MARKER_PREFIX}host=${host} -->`) ||
      content.includes(`${OWNER_TS_MARKER_PREFIX}host=${host}`) ||
      content.includes(`${OWNER_YAML_MARKER_PREFIX}host=${host}`)
  );
}

async function obsoleteGeneratedItems(
  cwd: string,
  host: CommandHostSelection,
  wantedPaths: Set<string>
): Promise<CommandInstallPlanItem[]> {
  const hosts = new Set<ActiveCommandHost>(selectedHosts(host));
  const roots = selectedHosts(host).flatMap(
    (selectedHost) => GENERATED_RESOURCE_ROOTS[selectedHost]
  );
  const files = await Promise.all(
    roots.map((root) => listFiles(join(cwd, root)))
  );
  return files
    .flat()
    .flatMap((absolutePath) => {
      const content = readFileSync(absolutePath, "utf8");
      const generatedHost = generatedHostFor(content);
      if (!(generatedHost && hosts.has(generatedHost))) {
        return [];
      }
      const path = relative(cwd, absolutePath).replaceAll("\\", "/");
      if (wantedPaths.has(path)) {
        return [];
      }
      return [
        {
          action: "delete" as const,
          host: generatedHost,
          invocation: invocationForHost(
            generatedHost,
            entrypointIdFromGeneratedPath(generatedHost, path)
          ),
          path,
        },
      ];
    })
    .sort((a, b) => a.path.localeCompare(b.path));
}

function entrypointIdFromGeneratedPath(
  host: ActiveCommandHost,
  path: string
): string | undefined {
  for (const pattern of ENTRYPOINT_PATH_PATTERNS[host]) {
    const match = pattern.exec(path);
    if (match) {
      return match[1];
    }
  }
  return;
}

function invocationForHost(
  host: ActiveCommandHost,
  entrypointId = "execute"
): string {
  const prefix: Record<ActiveCommandHost, string> = {
    opencode: "/",
  };
  return `${prefix[host]}${entrypointId} <task description>`;
}

interface ResolvedCommandDefinitionContent {
  conflict: boolean;
  content: string;
}

function resolveDefinitionContent(
  definition: CommandDefinition,
  target: string
): ResolvedCommandDefinitionContent {
  if (definition.path !== OPENCODE_PROJECT_CONFIG_PATH || !existsSync(target)) {
    return { conflict: false, content: definition.content };
  }

  const projection = JSON.parse(definition.content) as Record<string, unknown>;
  const merged = mergeOpenCodeProjectConfig(
    readFileSync(target, "utf8"),
    projection
  );
  if (!merged.ok) {
    return { conflict: true, content: definition.content };
  }
  return { conflict: false, content: merged.content };
}

function actionFor(
  path: string,
  content: string,
  force: boolean,
  block?: CommandDefinition["block"]
): InstallAction {
  if (!existsSync(path)) {
    return "create";
  }
  const current = readFileSync(path, "utf8");
  if (block) {
    if (current.includes(content.trimEnd())) {
      return "unchanged";
    }
    return "update";
  }
  if (current === content) {
    return "unchanged";
  }
  if (
    !(
      current.includes(GENERATED_MARKER) ||
      current.includes(GENERATED_TS_MARKER) ||
      current.includes(GENERATED_YAML_MARKER) ||
      force
    )
  ) {
    return "conflict";
  }
  return "update";
}

function upsertGeneratedBlock(
  current: string,
  content: string,
  block: NonNullable<CommandDefinition["block"]>
): string {
  const startIndex = current.indexOf(block.start);
  const endIndex = current.indexOf(block.end);
  if (startIndex >= 0 && endIndex >= startIndex) {
    const afterEnd = endIndex + block.end.length;
    const lineEnd = current.indexOf("\n", afterEnd);
    const replaceEnd = lineEnd >= 0 ? lineEnd + 1 : afterEnd;
    return `${current.slice(0, startIndex)}${content}${current.slice(replaceEnd)}`;
  }
  const separator = current.trimEnd().length > 0 ? "\n\n" : "";
  return `${current.trimEnd()}${separator}${content}`;
}

function installActionForDefinition(
  definition: CommandDefinition,
  target: string,
  resolved: ResolvedCommandDefinitionContent,
  force: boolean
): InstallAction {
  if (resolved.conflict) {
    return "conflict";
  }
  return actionFor(
    target,
    resolved.content,
    force || definition.path === OPENCODE_PROJECT_CONFIG_PATH,
    definition.block
  );
}

async function writeDefinition(
  definition: CommandDefinition,
  target: string,
  content: string
): Promise<void> {
  await mkdir(dirname(target), { recursive: true });
  if (definition.block && existsSync(target)) {
    await writeFile(
      target,
      upsertGeneratedBlock(
        readFileSync(target, "utf8"),
        content,
        definition.block
      )
    );
    return;
  }
  await writeFile(target, content);
}

function shouldSkipInstallWrite(
  options: InstallCommandsOptions,
  action: InstallAction
): boolean {
  return Boolean(
    options.check ||
      options.dryRun ||
      action === "unchanged" ||
      action === "conflict"
  );
}

async function installDefinition(
  cwd: string,
  definition: CommandDefinition,
  options: InstallCommandsOptions
): Promise<CommandInstallPlanItem> {
  const target = join(cwd, definition.path);
  const resolved = resolveDefinitionContent(definition, target);
  const action = installActionForDefinition(
    definition,
    target,
    resolved,
    Boolean(options.force)
  );
  const item = commandInstallPlanItem(definition, action);
  if (!shouldSkipInstallWrite(options, action)) {
    await writeDefinition(definition, target, resolved.content);
  }
  return item;
}

function commandInstallPlanItem(
  definition: CommandDefinition,
  action: InstallAction
): CommandInstallPlanItem {
  return {
    action,
    host: definition.host,
    invocation: definition.invocation,
    path: definition.path,
  };
}

function installCommandsContext(
  options: InstallCommandsOptions
): InstallCommandsContext {
  const cwd = options.cwd ?? process.cwd();
  const host = options.host ?? "all";
  const config = loadPipelineConfig(cwd, {
    allowMissingLintFileReferences: true,
  });
  const definitions = definitionsFor(host, config, cwd);
  return {
    cwd,
    definitions,
    host,
    wantedPaths: new Set(definitions.map((definition) => definition.path)),
  };
}

async function installDefinitions(
  cwd: string,
  definitions: CommandDefinition[],
  options: InstallCommandsOptions
): Promise<CommandInstallPlanItem[]> {
  const items: CommandInstallPlanItem[] = [];
  for (const definition of definitions) {
    items.push(await installDefinition(cwd, definition, options));
  }
  return items;
}

function shouldRemoveObsoleteItems(options: InstallCommandsOptions): boolean {
  return !(options.check || options.dryRun);
}

async function removeObsoleteItems(
  cwd: string,
  items: CommandInstallPlanItem[],
  options: InstallCommandsOptions
): Promise<void> {
  if (!shouldRemoveObsoleteItems(options)) {
    return;
  }
  for (const item of items) {
    await rm(join(cwd, item.path), { force: true });
  }
}

function actionIsConflict(item: CommandInstallPlanItem): boolean {
  return item.action === "conflict";
}

function actionIsChanged(item: CommandInstallPlanItem): boolean {
  return item.action !== "unchanged";
}

function assertNoInstallConflicts(
  options: InstallCommandsOptions,
  items: CommandInstallPlanItem[]
): void {
  if (options.dryRun) {
    return;
  }
  const conflicts = items.filter(actionIsConflict);
  if (conflicts.length === 0) {
    return;
  }
  throw new Error(
    [
      "Refusing to overwrite manually edited command files.",
      ...conflicts.map((item) => `- ${item.path}`),
      "Re-run with --force to overwrite them.",
    ].join("\n")
  );
}

function assertInstallCheckCurrent(
  options: InstallCommandsOptions,
  items: CommandInstallPlanItem[]
): void {
  if (!options.check) {
    return;
  }
  const changedItems = items.filter(actionIsChanged);
  if (changedItems.length === 0) {
    return;
  }
  throw new Error(
    [
      "Installed command files are not up to date.",
      ...changedItems.map((item) => `- ${item.path}: ${item.action}`),
    ].join("\n")
  );
}

export async function installCommands(
  options: InstallCommandsOptions = {}
): Promise<InstallCommandsResult> {
  const context = installCommandsContext(options);
  const items = await installDefinitions(
    context.cwd,
    context.definitions,
    options
  );
  const obsoleteItems = await obsoleteGeneratedItems(
    context.cwd,
    context.host,
    context.wantedPaths
  );
  items.push(...obsoleteItems);
  await removeObsoleteItems(context.cwd, obsoleteItems, options);
  assertNoInstallConflicts(options, items);
  assertInstallCheckCurrent(options, items);
  return { items };
}

export function parseCommandHost(
  value: string | undefined
): CommandHostSelection {
  const host = value ?? "all";
  if (host === "all" || COMMAND_HOSTS.includes(host as ActiveCommandHost)) {
    return host as CommandHostSelection;
  }
  throw new Error(
    `Unsupported host "${host}". Supported values: all, ${COMMAND_HOSTS.join(", ")}.`
  );
}

export function formatInstallCommandsResult(
  result: InstallCommandsResult
): string {
  return result.items
    .map(
      (item) => `${item.action} ${item.host}: ${item.path} (${item.invocation})`
    )
    .join("\n");
}
