import { existsSync, readFileSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative } from "node:path";
import matter from "gray-matter";
import { stringify as stringifyToml } from "smol-toml";
import { loadPipelineConfig, type PipelineConfig } from "./config.js";
import { renderCodexGatewayConfig } from "./mcp/gateway.js";
import { resolveFileReference } from "./path-refs.js";
import { compileWorkflowPlan } from "./workflow-planner.js";

const GENERATED_MARKER = "<!-- Generated by @oisincoveney/pipeline. -->";
const GENERATED_TS_MARKER = "// Generated by @oisincoveney/pipeline.";
const GENERATED_YAML_MARKER = "# Generated by @oisincoveney/pipeline.";
const OWNER_MARKER_PREFIX = "<!-- @oisincoveney/pipeline:";
const OWNER_TS_MARKER_PREFIX = "// @oisincoveney/pipeline:";
const OWNER_YAML_MARKER_PREFIX = "# @oisincoveney/pipeline:";
const CODEX_PLUGIN_COMMAND_ROOT = ".agents/plugins/oisin-pipeline/commands";
const CODEX_AGENT_CONFIG_START = "# @oisincoveney/pipeline:codex-agents:start";
const CODEX_AGENT_CONFIG_END = "# @oisincoveney/pipeline:codex-agents:end";
const CODEX_AGENTS_MD_START = "<!-- @oisincoveney/pipeline:agents:start -->";
const CODEX_AGENTS_MD_END = "<!-- @oisincoveney/pipeline:agents:end -->";
const ENTRYPOINT_PATH_PATTERNS: Record<ActiveCommandHost, RegExp[]> = {
  codex: [
    /^\.agents\/skills\/([^/]+)\/SKILL\.md$/,
    /^\.agents\/plugins\/oisin-pipeline\/commands\/([^/]+)\.md$/,
  ],
  opencode: [/^\.opencode\/commands\/([^/]+)\.md$/],
};
export const COMMAND_HOSTS = ["opencode", "codex"] as const;

type ActiveCommandHost = (typeof COMMAND_HOSTS)[number];
export type CommandHost = ActiveCommandHost;
export type CommandHostSelection = ActiveCommandHost | "all";
export type InstallAction =
  | "conflict"
  | "create"
  | "delete"
  | "unchanged"
  | "update";

export interface CommandInstallPlanItem {
  action: InstallAction;
  host: CommandHost;
  invocation: string;
  path: string;
}

export interface InstallCommandsOptions {
  check?: boolean;
  cwd?: string;
  dryRun?: boolean;
  force?: boolean;
  host?: CommandHostSelection;
}

export interface InstallCommandsResult {
  items: CommandInstallPlanItem[];
}

interface CommandDefinition {
  block?: {
    end: string;
    start: string;
  };
  content: string;
  host: ActiveCommandHost;
  invocation: string;
  path: string;
}

type EntrypointEntry = [string, PipelineConfig["entrypoints"][string]];
type ProfileEntry = [string, PipelineConfig["profiles"][string]];
type ActorConfig = PipelineConfig["profiles"][string];

interface OpencodePermissionOptions {
  allowedTaskAgents?: string[];
}

type DispatchKind = "cli" | "native-model-agent" | "native-named-agent";

interface AgentDispatchRoute {
  kind: DispatchKind;
  model?: string;
  nativeAgentId?: string;
  needs: string[];
  nodeId: string;
  profile: PipelineConfig["profiles"][string];
  profileId: string;
  runnerId: string;
}

function header(host: ActiveCommandHost): string {
  return [GENERATED_MARKER, `${OWNER_MARKER_PREFIX}host=${host} -->`, ""].join(
    "\n"
  );
}

function markdown(data: Record<string, unknown>, body: string): string {
  return `${matter.stringify(body.trimEnd(), data).trimEnd()}\n`;
}

function profileEntries(config: PipelineConfig): ProfileEntry[] {
  const profileIds = new Set<string>();
  for (const workflow of Object.values(config.workflows)) {
    for (const node of workflow.nodes) {
      if (node.kind === "agent" && node.profile) {
        profileIds.add(node.profile);
      }
    }
  }
  return [...profileIds]
    .sort((a, b) => a.localeCompare(b))
    .map((id) => [id, config.profiles[id]] as ProfileEntry);
}

function entrypointEntries(config: PipelineConfig): EntrypointEntry[] {
  const entries = Object.entries(config.entrypoints);
  return entries.length > 0
    ? entries
    : [
        [
          "pipe",
          {
            description: "Run the configured pipeline workflow",
            workflow: config.default_workflow,
          },
        ],
      ];
}

function entrypointDescription(
  id: string,
  entrypoint: PipelineConfig["entrypoints"][string]
): string {
  return entrypoint.description ?? `Run the ${id} workflow`;
}

function entrypointCommandDefinitions(
  _host: ActiveCommandHost,
  config: PipelineConfig,
  makeDefinition: (
    id: string,
    entrypoint: PipelineConfig["entrypoints"][string]
  ) => CommandDefinition
): CommandDefinition[] {
  return entrypointEntries(config).map(([id, entrypoint]) =>
    makeDefinition(id, entrypoint)
  );
}

function nativeProfileEntries(
  host: ActiveCommandHost,
  config: PipelineConfig
): ProfileEntry[] {
  return profileEntries(config).filter(([_, profile]) =>
    canRunNatively(host, config, profile)
  );
}

function orchestratorProfile(config: PipelineConfig): ActorConfig {
  const profile = config.profiles[config.orchestrator.profile];
  if (!profile) {
    throw new Error(
      `Orchestrator profile '${config.orchestrator.profile}' is not declared.`
    );
  }
  return {
    ...profile,
  };
}

function resolvedHostModel(
  config: PipelineConfig,
  host: ActiveCommandHost,
  profile: PipelineConfig["profiles"][string]
): string | undefined {
  const runner = config.runners[profile.runner];
  const hostRunner = config.runners[host];
  if (profile.host_models?.[host]) {
    return profile.host_models[host];
  }
  if (runner?.host_models?.[host]) {
    return runner.host_models[host];
  }
  if (profile.runner === host) {
    return profile.model ?? runner?.model;
  }
  return hostRunner?.model;
}

function canRunNatively(
  host: ActiveCommandHost,
  config: PipelineConfig,
  profile: PipelineConfig["profiles"][string]
): boolean {
  if (profile.runner === host) {
    if (host === "codex") {
      return resolvedHostModel(config, host, profile) !== undefined;
    }
    return true;
  }
  return host === "opencode" && isModelRunner(profile.runner);
}

function isModelRunner(runnerId: string): boolean {
  return COMMAND_HOSTS.some((host) => host === runnerId);
}

function agentDispatchRoutes(
  host: ActiveCommandHost,
  config: PipelineConfig,
  workflowId = config.default_workflow
): AgentDispatchRoute[] {
  const plan = compileWorkflowPlan(config, workflowId);
  return plan.topologicalOrder.flatMap((node) => {
    if (!(node.kind === "agent" && node.profile)) {
      return [];
    }
    const profile = config.profiles[node.profile];
    if (!profile) {
      return [];
    }
    return [
      dispatchRouteForAgent(host, config, {
        needs: node.needs,
        nodeId: node.id,
        profile,
        profileId: node.profile,
      }),
    ];
  });
}

function dispatchRouteForAgent(
  host: ActiveCommandHost,
  config: PipelineConfig,
  route: Pick<AgentDispatchRoute, "needs" | "nodeId" | "profile" | "profileId">
): AgentDispatchRoute {
  const runnerId = route.profile.runner;
  if (runnerId === host) {
    const model = resolvedHostModel(config, host, route.profile);
    if (host === "codex" && !model) {
      throw new Error(
        `profile '${route.profileId}' cannot be represented as a native Codex agent because no Codex model resolves`
      );
    }
    return {
      ...route,
      kind: "native-named-agent",
      ...(model ? { model } : {}),
      nativeAgentId: route.profileId,
      runnerId,
    };
  }
  if (host === "opencode" && isModelRunner(runnerId)) {
    const model = resolvedHostModel(config, host, route.profile);
    return {
      ...route,
      kind: "native-model-agent",
      ...(model ? { model } : {}),
      nativeAgentId: route.profileId,
      runnerId,
    };
  }
  return {
    ...route,
    kind: "cli",
    runnerId,
  };
}

function grants(actor: ActorConfig): string {
  return [
    `model: ${actor.model ?? "default"}`,
    `tools: ${(actor.tools ?? []).join(", ") || "none"}`,
    `rules: ${(actor.rules ?? []).join(", ") || "none"}`,
    `skills: ${(actor.skills ?? []).join(", ") || "none"}`,
    `mcp_servers: ${(actor.mcp_servers ?? []).join(", ") || "none"}`,
    `filesystem: ${actor.filesystem?.mode ?? "default"}`,
    `network: ${actor.network?.mode ?? "default"}`,
    ...("output" in actor ? [`output: ${actor.output?.format ?? "text"}`] : []),
  ].join("\n");
}

function outputContract(actor: ActorConfig): string {
  const output = actor.output;
  if (!output) {
    return "";
  }
  return [
    ...(output.schema_path
      ? [`output_schema_path: ${output.schema_path}`]
      : []),
    ...(output.repair?.enabled === undefined
      ? []
      : [`output_repair_enabled: ${String(output.repair.enabled)}`]),
    ...(output.repair?.max_attempts
      ? [`output_repair_max_attempts: ${output.repair.max_attempts}`]
      : []),
  ].join("\n");
}

function orchestratorBlock(config: PipelineConfig): string {
  return [
    "Configured orchestrator:",
    grants(orchestratorProfile(config)),
    `hooks: ${Object.keys(config.hooks.functions).join(", ") || "none"}`,
    "",
    instructionsPointer(orchestratorProfile(config)),
  ].join("\n");
}

function dispatchBlock(
  host: ActiveCommandHost,
  config: PipelineConfig,
  workflowId = config.default_workflow
): string | undefined {
  const routes = agentDispatchRoutes(host, config, workflowId);
  if (routes.length === 0) {
    return;
  }
  const plan = compileWorkflowPlan(config, workflowId);
  const nativeRoutes = routes.filter((route) => route.kind !== "cli");
  const cliRoutes = routes.filter((route) => route.kind === "cli");
  return [
    `Run workflow \`${plan.workflowId}\` for the user task.`,
    "",
    nativeDispatchBlock(host, nativeRoutes),
    cliDispatchBlock(host, cliRoutes),
    nodePromptContract(plan.workflowId, routes),
    "Only package-configured gates are blocking. Do not invent RED, GREEN, full-suite, typecheck, or unrelated-drift gates.",
    "If a node returns targeted evidence and has no configured blocking gate, advance to the next workflow node.",
    "Do not use `pipe`, `oisin-pipeline`, or package scripts to execute workflow nodes.",
    hostSpecificDispatchGuard(host, nativeRoutes, cliRoutes),
  ]
    .filter((line): line is string => Boolean(line))
    .join("\n");
}

function entrypointDispatchBlock(
  host: ActiveCommandHost,
  config: PipelineConfig,
  id: string,
  entrypoint: PipelineConfig["entrypoints"][string]
): string | undefined {
  if ("workflow" in entrypoint) {
    return dispatchBlock(host, config, entrypoint.workflow);
  }
  return [
    `Generate a schedule for entrypoint \`${id}\` and the user task.`,
    `The schedule policy is \`${entrypoint.schedule}\`.`,
    `Run \`pipe run --entrypoint ${id} <task description>\` to generate and execute the schedule artifact.`,
    "The pipeline CLI runtime is the deterministic graph scheduler for scheduled entrypoints.",
    "It launches configured Codex/OpenCode agent subprocesses as soon as their dependencies pass.",
    "Use `pipe run --schedule <schedule.yaml>` only when rerunning an existing schedule artifact.",
  ].join("\n");
}

function nativeDispatchBlock(
  host: ActiveCommandHost,
  routes: AgentDispatchRoute[]
): string | undefined {
  if (routes.length === 0) {
    return;
  }
  return [
    `${hostDisplayName(host)} native routes:`,
    ...routes.map((route) => nativeDispatchLine(host, route)),
    "",
  ].join("\n");
}

function nativeDispatchLine(
  host: ActiveCommandHost,
  route: AgentDispatchRoute
): string {
  const needs = needsSummary(route.needs);
  if (host === "codex") {
    const model = route.model ? ` model=${route.model}` : "";
    return `- ${route.nodeId}: spawn_agent agent_type=${route.nativeAgentId}${model} runner=${route.runnerId} needs=${needs}`;
  }
  const model = route.model ? ` model=${route.model}` : "";
  return `- ${route.nodeId}: Task tool subagent_type=${route.nativeAgentId}${model} runner=${route.runnerId} needs=${needs}`;
}

function cliDispatchBlock(
  host: ActiveCommandHost,
  routes: AgentDispatchRoute[]
): string | undefined {
  if (routes.length === 0) {
    return;
  }
  const nativeNotice = `These nodes are not ${hostDisplayName(host)} native routes.`;
  return [nativeNotice, "CLI routes:", ...routes.map(cliDispatchLine), ""].join(
    "\n"
  );
}

function cliDispatchLine(route: AgentDispatchRoute): string {
  return `- ${route.nodeId}: ${route.runnerId} CLI profile=${route.profileId} command=\`${runnerCliCommand(route)}\` needs=${needsSummary(route.needs)}`;
}

function runnerCliCommand(route: AgentDispatchRoute): string {
  if (route.runnerId === "opencode") {
    return `opencode run --agent ${route.profileId} --format json --dir <repo-root> <node prompt>`;
  }
  throw new Error(
    `runner '${route.runnerId}' cannot be represented as a supported native or CLI route`
  );
}

function nodePromptContract(
  workflowId: string,
  routes: AgentDispatchRoute[]
): string {
  const hasCliRoutes = routes.some((route) => route.kind === "cli");
  const lead = hasCliRoutes
    ? "For each CLI node prompt include:"
    : "For each native node prompt include:";
  return [
    lead,
    "- user task",
    `- workflow id: ${workflowId}`,
    "- node id",
    "- profile id",
    "- runner id",
    "- profile instructions reference",
    "- profile grants",
    "- dependency outputs",
    "",
  ].join("\n");
}

function hostSpecificDispatchGuard(
  host: ActiveCommandHost,
  nativeRoutes: AgentDispatchRoute[],
  cliRoutes: AgentDispatchRoute[]
): string | undefined {
  if (host === "codex" && nativeRoutes.length > 0) {
    return "Do not substitute the generic Codex worker for configured profiles.";
  }
  if (cliRoutes.length > 0 && nativeRoutes.length > 0) {
    return `Do not claim CLI routes are ${hostDisplayName(host)} native routes.`;
  }
  if (cliRoutes.length > 0 && nativeRoutes.length === 0) {
    return `Do not claim these nodes are ${hostDisplayName(host)} subagents.`;
  }
  return;
}

function hostDisplayName(host: ActiveCommandHost): string {
  const names: Record<ActiveCommandHost, string> = {
    codex: "Codex",
    opencode: "OpenCode",
  };
  return names[host];
}

function needsSummary(needs: string[]): string {
  return needs.length > 0 ? needs.join(",") : "none";
}

function compactLines(lines: Array<string | undefined>): string[] {
  return lines.filter((line): line is string => line !== undefined);
}

function opencodePermission(
  actor: ActorConfig,
  options: OpencodePermissionOptions = {}
): Record<string, string | Record<string, string>> {
  const allowed = new Set(actor.tools ?? []);
  let taskPermission: string | Record<string, string>;
  if (options.allowedTaskAgents && options.allowedTaskAgents.length > 0) {
    taskPermission = {
      "*": "deny",
      ...Object.fromEntries(
        options.allowedTaskAgents.map((agent) => [agent, "allow"])
      ),
    };
  } else {
    taskPermission = allowed.has("task") ? "allow" : "deny";
  }
  return {
    bash: allowed.has("bash") ? "allow" : "deny",
    edit: allowed.has("edit") ? "allow" : "deny",
    glob: allowed.has("glob") ? "allow" : "deny",
    grep: allowed.has("grep") ? "allow" : "deny",
    list: allowed.has("list") ? "allow" : "deny",
    read: allowed.has("read") ? "allow" : "deny",
    task: taskPermission,
    write: allowed.has("write") ? "allow" : "deny",
  };
}

function opencodeDefinitions(
  config: PipelineConfig,
  cwd: string
): CommandDefinition[] {
  return [
    ...entrypointCommandDefinitions("opencode", config, (id, entrypoint) => ({
      content: markdown(
        {
          agent: "pipeline-orchestrator",
          description: entrypointDescription(id, entrypoint),
        },
        compactLines([
          header("opencode").trimEnd(),
          "",
          `Invoke this command with \`${invocationForHost("opencode", id)}\`.`,
          "",
          orchestratorBlock(config),
          "",
          entrypointDispatchBlock("opencode", config, id, entrypoint),
        ]).join("\n")
      ),
      host: "opencode",
      invocation: invocationForHost("opencode", id),
      path: `.opencode/commands/${id}.md`,
    })),
    {
      content: markdown(
        {
          description: "Orchestrate the configured pipeline and enforce gates.",
          mode: "primary",
          permission: opencodePermission(orchestratorProfile(config), {
            allowedTaskAgents: agentDispatchRoutes("opencode", config)
              .filter((route) => route.kind !== "cli")
              .map((route) => route.nativeAgentId)
              .filter((id): id is string => Boolean(id)),
          }),
        },
        compactLines([
          header("opencode").trimEnd(),
          "",
          orchestratorBlock(config),
          "",
          dispatchBlock("opencode", config),
        ]).join("\n")
      ),
      host: "opencode",
      invocation: invocationForHost("opencode"),
      path: ".opencode/agents/pipeline-orchestrator.md",
    },
    ...nativeProfileEntries("opencode", config).map(([id, profile]) => ({
      content: markdown(
        {
          description: profile.description ?? id,
          mode: "subagent",
          ...opencodeModelProjection(config, profile),
          permission: opencodePermission(profile),
        },
        [
          header("opencode").trimEnd(),
          "",
          profile.description ?? id,
          "",
          "Configured grants:",
          grants(profile),
          "",
          instructionsPointer(profile),
        ].join("\n")
      ),
      host: "opencode" as const,
      invocation: invocationForHost("opencode"),
      path: `.opencode/agents/${id}.md`,
    })),
    projectAgentsMdDefinition(cwd, "opencode"),
  ];
}

function codexDefinitions(
  config: PipelineConfig,
  cwd: string
): CommandDefinition[] {
  const nativeCodexProfiles = nativeProfileEntries("codex", config);
  return [
    ...entrypointCommandDefinitions("codex", config, (id, entrypoint) => ({
      content: markdown(
        {
          description: entrypointDescription(id, entrypoint),
          name: id,
        },
        compactLines([
          header("codex").trimEnd(),
          "",
          `Invoke this skill with \`${invocationForHost("codex", id)}\`.`,
          "",
          orchestratorBlock(config),
          "",
          entrypointDispatchBlock("codex", config, id, entrypoint),
        ]).join("\n")
      ),
      host: "codex",
      invocation: invocationForHost("codex", id),
      path: `.agents/skills/${id}/SKILL.md`,
    })),
    ...entrypointCommandDefinitions("codex", config, (id, entrypoint) => ({
      content: markdown(
        {
          "argument-hint": "<task description>",
          description: entrypointDescription(id, entrypoint),
        },
        compactLines([
          header("codex").trimEnd(),
          "",
          `Invoke this command with \`${codexPluginInvocation(id)}\`.`,
          "",
          "Use `$ARGUMENTS` as the user task. Require a non-empty task description.",
          "",
          orchestratorBlock(config),
          "",
          entrypointDispatchBlock("codex", config, id, entrypoint),
        ]).join("\n")
      ),
      host: "codex",
      invocation: codexPluginInvocation(id),
      path: `${CODEX_PLUGIN_COMMAND_ROOT}/${id}.md`,
    })),
    projectAgentsMdDefinition(cwd, "codex"),
    ...nativeCodexProfiles.map(([id, profile]) =>
      codexTomlAgentDefinition(config, cwd, id, profile)
    ),
    codexProjectConfigAgentDefinition(config),
  ];
}

function projectAgentsMdDefinition(
  cwd: string,
  host: ActiveCommandHost
): CommandDefinition {
  const repoName = basename(cwd);
  return {
    block: {
      end: CODEX_AGENTS_MD_END,
      start: CODEX_AGENTS_MD_START,
    },
    content: [
      CODEX_AGENTS_MD_START,
      GENERATED_MARKER,
      `${OWNER_MARKER_PREFIX}host=codex -->`,
      `${OWNER_MARKER_PREFIX}host=opencode -->`,
      "",
      "## Pipeline Guidance",
      "",
      "This repository uses package-owned `@oisincoveney/pipeline` config.",
      "",
      "- Use `$pipe`, `$inspect`, or `$epic` for Codex skill entrypoints when the user asks for pipeline workflows.",
      "- Use `/pipe`, `/inspect`, or `/epic` for Codex or OpenCode slash-command entrypoints when available.",
      "- Load and follow the relevant skill from `.agents/skills` before doing specialized work.",
      "- Prefer the package-defined pipeline profiles and generated command surfaces over ad hoc subagent prompts.",
      "",
      "## Pipeline Memory",
      "",
      `Use Qdrant collection \`${repoName}\` for this repository.`,
      "",
      `- Call \`qdrant-find\` before research with \`collection_name: ${repoName}\` unless the user explicitly disables memory.`,
      `- Call \`qdrant-store\` during LEARN with \`collection_name: ${repoName}\` for durable lessons worth reusing.`,
      "- Include metadata with at least `repo`, `phase`, `workflow` or `entrypoint`, `task`, and `outcome` when storing lessons.",
      "",
      CODEX_AGENTS_MD_END,
      "",
    ].join("\n"),
    host,
    invocation: invocationForHost(host),
    path: "AGENTS.md",
  };
}

function codexTomlAgentDefinition(
  config: PipelineConfig,
  cwd: string,
  id: string,
  profile: PipelineConfig["profiles"][string]
): CommandDefinition {
  const profileWithResolvedModel = {
    ...profile,
    model: resolvedHostModel(config, "codex", profile) ?? profile.model,
  };
  const skillConfig = codexSkillConfig(config, cwd, profile);
  const agentConfig = {
    name: id,
    description: profile.description ?? id,
    ...(profileWithResolvedModel.model
      ? { model: profileWithResolvedModel.model }
      : {}),
    ...(profile.filesystem?.mode
      ? { sandbox_mode: profile.filesystem.mode }
      : {}),
    developer_instructions: [
      `You are the configured Pipeline profile \`${id}\`.`,
      "",
      profile.description ?? id,
      "",
      "Configured grants:",
      grants(profileWithResolvedModel),
      outputContract(profileWithResolvedModel),
      "",
      "Use only the configured tools, filesystem mode, network mode, MCP servers, and output contract above for this profile.",
      "",
      codexAgentInstructions(cwd, profile),
    ].join("\n"),
    skills: { config: skillConfig },
  };
  return {
    content: [
      "# Generated by @oisincoveney/pipeline.",
      `${OWNER_YAML_MARKER_PREFIX}host=codex`,
      "",
      stringifyToml(agentConfig).trimEnd(),
      "",
    ].join("\n"),
    host: "codex" as const,
    invocation: invocationForHost("codex"),
    path: `.codex/agents/${id}.toml`,
  };
}

function codexAgentInstructions(
  cwd: string,
  profile: PipelineConfig["profiles"][string]
): string {
  if (profile.instructions.inline) {
    return ["Profile instructions:", "", profile.instructions.inline].join(
      "\n"
    );
  }
  if (profile.instructions.path) {
    const resolvedPath = resolveFileReference(cwd, profile.instructions.path);
    if (existsSync(resolvedPath)) {
      return [
        `Instructions source: ${profile.instructions.path}`,
        "",
        "Profile instructions:",
        "",
        readFileSync(resolvedPath, "utf8").trimEnd(),
      ].join("\n");
    }
  }
  return instructionsPointer(profile);
}

function codexSkillConfig(
  config: PipelineConfig,
  cwd: string,
  profile: PipelineConfig["profiles"][string]
): Record<string, unknown>[] {
  return (profile.skills ?? []).flatMap((id) => {
    const path = config.skills[id]?.path;
    if (!path) {
      return [];
    }
    const absolutePath = resolveFileReference(cwd, path);
    if (!existsSync(absolutePath)) {
      return [];
    }
    return [{ enabled: true, path }];
  });
}

function codexProjectConfigAgentDefinition(
  config: PipelineConfig
): CommandDefinition {
  return {
    block: {
      end: CODEX_AGENT_CONFIG_END,
      start: CODEX_AGENT_CONFIG_START,
    },
    content: [
      ...(config.mcp_gateway
        ? [renderCodexGatewayConfig(config).trimEnd(), ""]
        : []),
      CODEX_AGENT_CONFIG_START,
      stringifyToml({ agents: { max_depth: 1 } }).trimEnd(),
      CODEX_AGENT_CONFIG_END,
      "",
    ].join("\n"),
    host: "codex" as const,
    invocation: invocationForHost("codex"),
    path: ".codex/config.toml",
  };
}

function opencodeModelProjection(
  config: PipelineConfig,
  profile: PipelineConfig["profiles"][string]
): Record<string, string> {
  const model = resolvedHostModel(config, "opencode", profile);
  return model ? { model } : {};
}

function instructionsPointer(actor: ActorConfig): string {
  if (actor.instructions.path) {
    return `Instructions: ${actor.instructions.path}`;
  }
  return `Instructions:\n${actor.instructions.inline ?? ""}`;
}

function definitionsFor(
  host: CommandHostSelection,
  config: PipelineConfig,
  cwd: string
): CommandDefinition[] {
  const definitions: Record<ActiveCommandHost, () => CommandDefinition[]> = {
    codex: () => codexDefinitions(config, cwd),
    opencode: () => opencodeDefinitions(config, cwd),
  };
  const hosts = host === "all" ? COMMAND_HOSTS : [host];
  const rawDefinitions = hosts.flatMap((name) => definitions[name]());
  return dedupeDefinitionsByPath(rawDefinitions);
}

function dedupeDefinitionsByPath(
  definitions: CommandDefinition[]
): CommandDefinition[] {
  const lastIndexes = new Map<string, number>();
  definitions.forEach((definition, index) => {
    lastIndexes.set(definition.path, index);
  });
  return definitions.filter(
    (definition, index) => lastIndexes.get(definition.path) === index
  );
}

function selectedHosts(host: CommandHostSelection): ActiveCommandHost[] {
  return host === "all" ? [...COMMAND_HOSTS] : [host];
}

const GENERATED_RESOURCE_ROOTS: Record<ActiveCommandHost, string[]> = {
  codex: [".agents/skills", ".codex/agents", CODEX_PLUGIN_COMMAND_ROOT],
  opencode: [".opencode/commands", ".opencode/agents"],
};

async function listFiles(root: string): Promise<string[]> {
  if (!existsSync(root)) {
    return [];
  }
  const entries = await readdir(root, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const path = join(root, entry.name);
      if (entry.isDirectory()) {
        return listFiles(path);
      }
      return [path];
    })
  );
  return files.flat();
}

function generatedHostFor(content: string): CommandHost | undefined {
  return COMMAND_HOSTS.find(
    (host) =>
      content.includes(`${OWNER_MARKER_PREFIX}host=${host} -->`) ||
      content.includes(`${OWNER_TS_MARKER_PREFIX}host=${host}`) ||
      content.includes(`${OWNER_YAML_MARKER_PREFIX}host=${host}`)
  );
}

async function obsoleteGeneratedItems(
  cwd: string,
  host: CommandHostSelection,
  wantedPaths: Set<string>
): Promise<CommandInstallPlanItem[]> {
  const hosts = new Set<CommandHost>(selectedHosts(host));
  const roots = selectedHosts(host).flatMap(
    (selectedHost) => GENERATED_RESOURCE_ROOTS[selectedHost]
  );
  const files = await Promise.all(
    roots.map((root) => listFiles(join(cwd, root)))
  );
  return files
    .flat()
    .flatMap((absolutePath) => {
      const content = readFileSync(absolutePath, "utf8");
      const generatedHost = generatedHostFor(content);
      if (!(generatedHost && hosts.has(generatedHost))) {
        return [];
      }
      const path = relative(cwd, absolutePath).replaceAll("\\", "/");
      if (wantedPaths.has(path)) {
        return [];
      }
      return [
        {
          action: "delete" as const,
          host: generatedHost,
          invocation: invocationForHost(
            generatedHost,
            entrypointIdFromGeneratedPath(generatedHost, path)
          ),
          path,
        },
      ];
    })
    .sort((a, b) => a.path.localeCompare(b.path));
}

function entrypointIdFromGeneratedPath(
  host: CommandHost,
  path: string
): string | undefined {
  for (const pattern of ENTRYPOINT_PATH_PATTERNS[host]) {
    const match = pattern.exec(path);
    if (match) {
      return match[1];
    }
  }
  return;
}

function invocationForHost(host: CommandHost, entrypointId = "pipe"): string {
  const prefix: Record<CommandHost, string> = {
    codex: "$",
    opencode: "/",
  };
  return `${prefix[host]}${entrypointId} <task description>`;
}

function codexPluginInvocation(entrypointId: string): string {
  return `/${entrypointId} <task description>`;
}

function actionFor(
  path: string,
  content: string,
  force: boolean,
  block?: CommandDefinition["block"]
): InstallAction {
  if (!existsSync(path)) {
    return "create";
  }
  const current = readFileSync(path, "utf8");
  if (block) {
    if (current.includes(content.trimEnd())) {
      return "unchanged";
    }
    return "update";
  }
  if (current === content) {
    return "unchanged";
  }
  if (
    !(
      current.includes(GENERATED_MARKER) ||
      current.includes(GENERATED_TS_MARKER) ||
      current.includes(GENERATED_YAML_MARKER) ||
      force
    )
  ) {
    return "conflict";
  }
  return "update";
}

function upsertGeneratedBlock(
  current: string,
  content: string,
  block: NonNullable<CommandDefinition["block"]>
): string {
  const startIndex = current.indexOf(block.start);
  const endIndex = current.indexOf(block.end);
  if (startIndex >= 0 && endIndex >= startIndex) {
    const afterEnd = endIndex + block.end.length;
    const lineEnd = current.indexOf("\n", afterEnd);
    const replaceEnd = lineEnd >= 0 ? lineEnd + 1 : afterEnd;
    return `${current.slice(0, startIndex)}${content}${current.slice(replaceEnd)}`;
  }
  const separator = current.trimEnd().length > 0 ? "\n\n" : "";
  return `${current.trimEnd()}${separator}${content}`;
}

export async function installCommands(
  options: InstallCommandsOptions = {}
): Promise<InstallCommandsResult> {
  const cwd = options.cwd ?? process.cwd();
  const host = options.host ?? "all";
  const config = loadPipelineConfig(cwd, {
    allowMissingLintFileReferences: true,
  });
  const items: CommandInstallPlanItem[] = [];
  const definitions = definitionsFor(host, config, cwd);
  const wantedPaths = new Set(definitions.map((definition) => definition.path));

  for (const definition of definitions) {
    const target = join(cwd, definition.path);
    const action = actionFor(
      target,
      definition.content,
      Boolean(options.force),
      definition.block
    );
    items.push({
      action,
      host: definition.host,
      invocation: definition.invocation,
      path: definition.path,
    });

    if (options.check || options.dryRun || action === "unchanged") {
      continue;
    }
    if (action === "conflict") {
      continue;
    }

    await mkdir(dirname(target), { recursive: true });
    if (definition.block && existsSync(target)) {
      await writeFile(
        target,
        upsertGeneratedBlock(
          readFileSync(target, "utf8"),
          definition.content,
          definition.block
        )
      );
    } else {
      await writeFile(target, definition.content);
    }
  }

  const obsoleteItems = await obsoleteGeneratedItems(cwd, host, wantedPaths);
  items.push(...obsoleteItems);
  if (!(options.check || options.dryRun)) {
    for (const item of obsoleteItems) {
      await rm(join(cwd, item.path), { force: true });
    }
  }

  if (!options.dryRun && items.some((item) => item.action === "conflict")) {
    throw new Error(
      [
        "Refusing to overwrite manually edited command files.",
        ...items
          .filter((item) => item.action === "conflict")
          .map((item) => `- ${item.path}`),
        "Re-run with --force to overwrite them.",
      ].join("\n")
    );
  }

  if (options.check && items.some((item) => item.action !== "unchanged")) {
    throw new Error(
      [
        "Installed command files are not up to date.",
        ...items
          .filter((item) => item.action !== "unchanged")
          .map((item) => `- ${item.path}: ${item.action}`),
      ].join("\n")
    );
  }

  return { items };
}

export function parseCommandHost(
  value: string | undefined
): CommandHostSelection {
  const host = value ?? "all";
  if (host === "all" || COMMAND_HOSTS.includes(host as ActiveCommandHost)) {
    return host as CommandHostSelection;
  }
  throw new Error(
    `Unsupported host "${host}". Supported values: all, ${COMMAND_HOSTS.join(", ")}.`
  );
}

export function formatInstallCommandsResult(
  result: InstallCommandsResult
): string {
  return result.items
    .map(
      (item) => `${item.action} ${item.host}: ${item.path} (${item.invocation})`
    )
    .join("\n");
}
